### ISSUE TITLE
Open files from the menu or command

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#104]
As a user I would like to be able to open files anywhere in the FS from the command palette or menu.

**Comment by hexa00** [comment]
I wish it wasn't a popup, more like an inline file navigation in the command palette but for now a popup would do.

It's just that now you can't open something outside of the navigator and it seems like a basic functionality someone would want.

**Comment by hexa00** [comment]
Yes , open->File  | open->Directory

In vscode however open directory switches the directory
But in atom open directory opens a new atom with the new directory

I like atom's approach since it allows to open multiple projects easily and still let you close if you want the last one, this also avoid issues like save all files before switching etc...

WDYT ?

**Comment by hexa00** [comment]
Just to give an idea of what I'm looking for ultimately, I would very much like something like the file open IDO mode provides in emacs like this gif:
![ido-file-open](https://cloud.githubusercontent.com/assets/698076/26060461/21bee7b8-3953-11e7-827f-55e9e7b6f3d2.gif)

The nice thing about this is that IDO remembers the last opened files so the first candidates are often good.

But first things firsts :)

**Comment by svenefftinge** [comment]
Considering a backend sitting on one workspace folder, I don't think we can spawn multiple frontends on different directories easily

**Comment by hexa00** [comment]
Couldn't we start a new instance of the frontend + backend ?

**Comment by hexa00** [comment]
We had a talk about this and realised we can't use a native dialog since this won't be tied to the backend FS service.

So I guess having a file open in the command palette would be better as a first step than a popup/dialog ?

**Comment by svenefftinge** [comment]
We have HTML rendered dialogs, though. They show up when creating resp. deleting a file or folder

**Comment by hexa00** [comment]
It's arguable to have a dialog or a command palette powered file open. 

I think we may have both but maybe it's faster to start with a command palette powered one like VSCode's without the '>' ?

Or maybe it's just me not being comfortable with the UI code yet, whatever seems easier works for me, as a first step

**Comment by svenefftinge** [comment]
I think a dialog would be easier, especially because we don't have the command palette, yet.

**Comment by hexa00** [comment]
We talked about this again recently and there was consensus that it would be nice to have the native dialogs if you're on electron and your backend is local.

**Comment by svenefftinge** [comment]
Could you explain why?

**Comment by hexa00** [comment]
@MarkZ3 do you want to comment this one ?

**Comment by MarkZ3** [comment]
I think some users will expect to see the native file chooser dialog as it is both familiar and has deeper integration with the operating-system/desktop-environment. It can be done later though, since there needs to be something in place that supports a remote backend anyway which should work with local too. I also think that the native file chooser dialog will likely be nicer to use (features, appearance, bugs) than any hand-written one and if we can give a better experience in one scenario (local + electron) then I think we should. This way we don't end up with a "lowest common denominator" kind of experience.
That said, I like the idea of opening files (including external but local) from the command palette as more experienced users will be able to do almost anything with the command palette using only the keyboard. So ideally both ways to open files should be there: a file chooser for new comers that are used to desktop IDEs/editors and the command palette for advanced users.
BTW, I just noticed that in VS Code, you can also do both, i.e. you can enter a full path in CMD/CTRL+P and it will open correctly (in addition to the file chooser). But I think Theia can do better in the command palette to hint that you can do that. Antoine suggested that we could display the full path of the workspace as a start (the last X characters) and the user could start typing a file under the workspace or type backspace to remove path segments and open other files external to the workspace. I think that would work nicely.

**Comment by svenefftinge** [comment]
I consider this fixed with #166.
