### ISSUE TITLE
Quick file open is slow

### ISSUE THREAD

**Issue by simark** [theia-ide/theia#1047]
With rather large workspaces (I use https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=summary), the quick file open dialog is somewhat slow.  After typing the first two characters, the results appear relatively fast.  However, after each subsequent character, it takes 2-3 seconds for the results to appear.  When typing multiple characters quickly (you can try typing "dwarf2loc"), it takes more time.  Presumably, the intermediate searches are not cancelled properly (that's just a guess).

**Comment by simark** [comment]
This might explain why the first two characters are fast:
https://github.com/theia-ide/theia/blob/master/packages/file-search/src/browser/quick-file-open.ts#L63

**Comment by svenefftinge** [comment]
For the record, as part of #1048 I also experimented with an async protocol. But I reverted it, because the experience was not better and the code was more complicated. It was slower and you could notice the results popping up one after another. 
For super large workspaces (>100000 files), it would be a bit better, though. But since that is not the usual case I didn't want to introduce compromises for the important 90%.
