### ISSUE TITLE
Remove accelerator from Keybinding structure

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#1089]
As discussed in #1065 

We need to remove accelerator and serialize the keybindings for Phosphor. 

We also need to serialize them for the user to see it properly in the menus.

**Comment by kittaakos** [comment]
Great! Also, please keep in mind, we need another accelerator implementation (hence binding) for the electron-based product. Back in that time, that's why I have added the [`AcceleratorProvider`](https://github.com/theia-ide/theia/blob/3284a605284e9c7de0ab416d5de98ef74c318314/packages/core/src/common/keys.ts#L12) which is not used at all now.

See: https://electronjs.org/docs/tutorial/keyboard-shortcuts

**Comment by hexa00** [comment]
OK thanks! I'll look into it.
