### ISSUE TITLE
[git] Move 'current' repository to status bar

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1091]
We should move the display of the currently selected git repository to the status bar and have a general command to change it using the quick command.

The name of the repo should be shortened to max 8 characters and be displays in front of the branch, only if there are other repos in the current workspace. Clicking the name shall trigger the 'Git: Change Repostory' command.

**Comment by kittaakos** [comment]
@svenefftinge, are there clear requirements how the buttons should look like after removing the drop-down widget for the Git View? Currently, it looks like this. +1 for aligning and/or changing it. It looks bad compared to other parts of the UI.

<img width="353" alt="screen shot 2018-01-23 at 11 25 06" src="https://user-images.githubusercontent.com/1405703/35270781-6a72d36c-0030-11e8-90bb-36bf7674f2f3.png">


Also, I would remove the margin too, so that the text input fields have a bigger space to stretch. What do you think?

CC: @akosyakov

**Comment by kittaakos** [comment]
We would like to move the command bar below the text fields. Have the `sync` button on the left, next to it the `...` more button. In the same line, there would be a real commit button.

```
+----------------------+
|                      |
+----------------------+

+----------------------+
|                      |
|                      |
+----------------------+

O ...           [Commit]
```

**Comment by lmcbout** [comment]
Question: is there any plan to add more git functionality on the button line like "git tree", git diff", "git merge" ?

**Comment by kittaakos** [comment]
I am not aware of it. For sure not part of this task. But we could move `git merge` and other commands under  the `...` (more) button. Would you like that approach?

**Comment by hexa00** [comment]
@kittaakos I like that idea with the commit button after the msg

**Comment by kittaakos** [comment]
Good, the credit goes to @svenefftinge, I just wrote down the things.

**Comment by lmcbout** [comment]
I don't know if those commands will be implemented eventually, but it would be nice to know and see how to integrate them with the new look & feel for the git buttons bar. 
Does the button bar is more visible on top or at the bottom ? Personally, I think we should put them on top since there is a list of folder and files that follow, so the buttons will be less visible if we put them between the file/folder and the commit text. May be with a line separator ?
Suggestion:
Also, can we make them not scrollable when we navigate through the file/folder, so the buttons are always visible when a user is on the git navigation window?

**Comment by kittaakos** [comment]
@lmcbout, could you please take care opening a follow-up task for the based on your [comment](https://github.com/theia-ide/theia/issues/1091#issuecomment-359810650)?

I personally, like the scrolling enhancement and the separator idea a lot, but I am not a huge fan of the many icons approach. Anyway, we can discuss and decide the requirements on the new follow-up once we add more and more Git features. Thank you!

**Comment by svenefftinge** [comment]
I don't see an issue with scrolling the form out of the view. After all, you are looking into your changes.

**Comment by kittaakos** [comment]
> @lmcbout, could you please take care opening a follow-up task for the based on your comment?

#1112.
