### ISSUE TITLE
Preferences can't be used in core

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#1170]
I would like to have a configurable timeout for example for keysquences but I can't :(

Because of the dependencies involved....
 
IMO we could need something like a peer dependency to fix that?

**Comment by akosyakov** [comment]
We can merge preferences-api to core and keep implementation in the separate extension.

**Comment by epatpol** [comment]
@kittaakos didn't you suggest we could maybe make preferences a part of @theia/core ? The thing is preference providers depend on workspace/userstorage/fs stuff... So that wouldn't work nicely. 

Unless we try an approach where the preference service is in core, *but* there's kind of an extension point where you can provide a json resource with a priority affected to it. i.e workspace provides a theia/settings.json file to core and userstorage also provides one with a lower priority. WDYT @akosyakov

**Comment by akosyakov** [comment]
@epatpol yes, let's first finish https://github.com/theia-ide/theia/pull/1158

**Comment by akosyakov** [comment]
preference api was merged into core by https://github.com/theia-ide/theia/pull/1195
