### ISSUE TITLE
Is there anyway to reuse vscode extensions?

### ISSUE THREAD

**Issue by sebastianmacias** [theia-ide/theia#1182]
I have been looking for a webbased vs code app for a while. Theia looks great. 

Is there a way to reuse existing vscode extensions? There are a few I can't work without like [vetur](https://github.com/vuejs/vetur) 

Thanks!

**Comment by akosyakov** [comment]
Hi @sebastianmacias, no, there is no way to run vscode extensions in Theia because they are too chatty to be run remotely: https://github.com/theia-ide/theia/issues/14#issuecomment-290691913.

The good news is that vetur relies on [the vetur language server](https://github.com/vuejs/vetur/tree/master/server) which can be reused in Theia. One needs to define the vue language with [Monarch](https://microsoft.github.io/monaco-editor/monarch.html) and then hook up the language server with it.

To get started you can have a look at existing language extensions for Theia.

**Comment by akosyakov** [comment]
Some links:
- https://github.com/theia-ide/theia/blob/master/doc/Authoring_Extensions.md - how to develop an extension
- the java extension shows how to define a Monarch tokenizer and register a new language for Monaco: https://github.com/theia-ide/theia/blob/master/packages/java/src/browser/monaco-contribution/index.ts
- the go extension shows how to hook up a language server: https://github.com/theia-ide/theia-go-extension

Feel free to ask more questions here and on [Gitter](https://gitter.im/theia-ide/theia).

**Comment by akosyakov** [comment]
https://github.com/rebornix/monaco-vue - monaco contribution for vue

**Comment by sebastianmacias** [comment]
Thanks for these resources @akosyakov. Would you consider having vue.js support come by default with theia?

**Comment by svenefftinge** [comment]
It should go into its own extension. We can create a project below `theia-ide` organization if you want. Also, we can include the extension in the JavaScript/TypeScript application at https://github.com/theia-ide/theia-apps

**Comment by vazexqi** [comment]
Should this issue be updated/closed based on the following announcement: https://medium.com/@sven.efftinge/theia-to-support-vs-code-extensions-a7b9100ec836 and also on-going work at https://github.com/theia-ide/theia/wiki/Testing-VS-Code-extensions
