### ISSUE TITLE
Send json-rpc processing to a webworker

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#1203]
From gitter:
I'm starting to think we may need to have a process just to process the network io...
or I should say the string manipulations that ensue..
or I did see a project that used web workers to have another thread greenlet I think ?
https://github.com/developit/greenlet could be an idea

In my profiling utf8ToBytes can take 500ms for a 3MB file which causes freezes while typing

**Comment by epatpol** [comment]
I've looked a bit into this:

So for `greenlet` there doesn't seem to be any working typings available on npm at the moment (looking at the latest version published) although there was indeed a PR [here](https://github.com/developit/greenlet/pull/4) merged recently. 

During my testing phase I wanted to try using web workers with `sendRequest` of `vscode-jsonrpc` by modifying `proxy-factory.ts`. The thing is the proxy is used both in the node environment and inside the browser environment. So we would need a polyfill (not sure how that would work here) for node so that the web workers translate to using node `process.fork` or something similar that works in the backend. 

@akosyakov if I wanted to use web workers and make them work in the backend, where should I start looking here? 

Also after discussing it here maybe the json-rpc communication isn't the best place to use web workers. I've thought about maybe more specific cases where monaco was lagging during a save, and one of the option was to move `file-resource.saveContents` to a web worker, but the thing is monaco could work with something else than a `file-resource`, so either all resources implement it, or I try to "thread" it up one level up.

I'm open to suggestions/comments.

**Comment by akosyakov** [comment]
We should not use web workers in node env. I was thinking about having json-rpc message reader and writer delegating to a web worker which does actual web socket communication

**Comment by hexa00** [comment]
Note that we could use a polyfil like this https://github.com/pgriess/node-webworker  to use webworker api in node.

But I'm not sure it's the best way ?

>I was thinking about having json-rpc message reader and writer delegating to a web worker which does actual web socket communication

I thought that was what @epatpol was tryting to do by wrapping sendRequest ? Or you mean something else ?

I mean the read/write of json has to be in the web worker too not just the websocket send right ? since most of the time is spent on the reader/writer string conversion.

**Comment by akosyakov** [comment]
I meant to go lower and replace the json-rpc transport layer with  https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/messageWriter.ts#L17 and https://github.com/Microsoft/vscode-languageserver-node/blob/master/jsonrpc/src/messageReader.ts#L106.

BTW how messages are passed between the main thread and workers? Are they get serialized? Won't it be the bottleneck? It could be that web workers are no solution at all and some improvements should be done in `vscode-jsonrpc`. I will need to look closer.

**Comment by hexa00** [comment]
>I meant to go lower and replace the json-rpc transport layer

OK

>BTW how messages are passed between the main thread and workers?

Looks like it's passed by object reference see : https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage

So it won't be an issue for the frontend.

For the backend however the polyfil uses websockets so yeah it doesn't make sense there.  We would need some kind of shared memory IPC communication for this to work...

**Comment by epatpol** [comment]
>It could be that web workers are no solution at all and some improvements should be done in vscode-jsonrpc

Sure!

>We should not use web workers in node env

Makes sense

As for the browser, there might be other cases where we want to use web workers no? Looking at vscode I think they have several for things like searching (although our search doesn't happen in the f-e, so it's a different use case), format etc. Maybe this might be worth testing/investigating in another issue though.

**Comment by epatpol** [comment]
>Looks like it's passed by object reference see : https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage

In that doc I see that `The data may be any value or JavaScript object handled by the structured clone algorithm` and looking at some others references it would seem that objects are passed by copy? Unless you use [Transferables](https://developer.mozilla.org/en-US/docs/Web/API/Transferable).

**Comment by epatpol** [comment]
FYI I'm not working on this anymore at the moment, but I had some stuff in my branch https://github.com/epatpol/theia-1/tree/threads for this. Not much, but just in case. Mainly related to webpack config and custom worker types.
