### ISSUE TITLE
Terminal restoration in bottom panel is not restoring the right size

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#1246]
If you open a terminal in the bottom panel, then expand the height of that bottom panel and click refresh.

The panel will be restored to a smaller height first, and then will be expanded but not to the full size it had before restore.

You can see the behavior in the websocket resize calls.

Observe the number of rows is smaller and then immediately gets bigger but not the the correct value.

You can also see it flicker a bit from the small size to the large size.

![terminal-restore](https://user-images.githubusercontent.com/698076/36032435-00d4d906-0d7c-11e8-8f8f-1edccded0867.gif)

**Comment by hexa00** [comment]
@spoenemann  ideas on that one ?

**Comment by spoenemann** [comment]
When the panel is restored, e.g. after reloading the page, its size is limited to a configurable ratio of the page height. If that causes more confusion than it helps, I can remove this "feature".

The flickering from the initial size to the restored size is because the size is set by adjusting the position of the split handle, and that can only be done asynchronously (at least I haven't found any other way to make it work). If I set the size immediately when the shell is constructed, that setting is lost after the shell is attached to the DOM, so instead I do it in a `window.requestAnimationFrame()`.

**Comment by hexa00** [comment]
I would agree that the feature is nice on the initial open, but not on restore.

So removing that part would be welcome, IMO.

But I guess this would not remove the flickering, the thing is I think there's some re-flow going on during that flickering and it causes issues with the terminal like having only 1 column.  But I need to validate this more.

Maybe not having the dom on restore is a problem that should be investigated after all...

**Comment by hexa00** [comment]
Also I tried adjusting the split handle directly to the size but somehow that didn't work as expected...

**Comment by spoenemann** [comment]
See also #1126.

I'll remove the maximal ratio.

Regarding the flickering, I can try whether I find a solution that sets the size immediately. Maybe we need to subclass SplitPanel, but the problem with that is that a lot of the Phosphor code is private and cannot be customized.

**Comment by hexa00** [comment]
Yes for the flickering I thought maybe we could investigate attaching the shell to the DOM prior to restoring the widgets that way it would be in the DOM from the start. And hide the intermediate state somehow so that we don't see flickering etc while it restores.  

Would that help?

**Comment by spoenemann** [comment]
Fixed in #1362 and #1413.

**Comment by hexa00** [comment]
Nice thx :)
