### ISSUE TITLE
[editor] Peek view after go to definition seems to be broken

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#1263]
Peek view should have a proper height, and should show references.

![2018-02-13 12 25 02](https://user-images.githubusercontent.com/914497/36147851-2054dc04-10ba-11e8-984a-6133ba4b4af2.gif)

Expectation:

<img width="1246" alt="screen shot 2018-02-13 at 12 37 04" src="https://user-images.githubusercontent.com/914497/36147997-a50f4f56-10ba-11e8-9a29-90d5e1d9f175.png">

**Comment by akosyakov** [comment]
It seems that the issue that calling `shell.addWidget` does not ensure that the attached widget is completely rendered, even though `widget.isAttached` and `widget.isVisible` return true, and monaco cannot render properly the reference widget without knowing editor node sizes.

The same problem will be applied to `shell.activateWidget`. One should await the activation event, otherwise monaco could perform changes on the previous active editor.

**Comment by akosyakov** [comment]
If someone has an idea how to detect that the widget is completely rendered, it would be very helpful.
