### ISSUE TITLE
Fix debugging workflow for theia and examples

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#131]
While trying to debug the browser example I get this situation:

Fixing the launch.json to be:
 "program": "${workspaceRoot}/examples/browser/lib/backend/main.js",

And trying to run it, it can't trigger breakpoints inside let's say theia/terminal/node/terminal-backend.ts

This is because the source map is generated with the path of theia inside the examples node_modules directory as such: "sources":["../../../src/terminal/node/terminal-backend-module.ts"],

Which gives theia/examples/browser/node_modules/theia/src

I'm not sure how to fix this properly...

**Comment by akosyakov** [comment]
Source maps are correct from the perspective of an extension developer. If you put the breakpoint into `myextension/node_modules/theia/src/terminal/node/terminal-backend-module.ts", it hits.

But true, it is not convenient for us. You can uncomment "sourceRoot" property in `tsconfig.json`, then source maps will use an absolute path on your disk. Please don't commit it uncommented though.

**Comment by hexa00** [comment]
Yes I understand, maybe it would make sense to have a script replace these paths.

I don't like to leave uncommited stuff lying around

I'll make a pull request just to change the program's path meanwhile

**Comment by akosyakov** [comment]
Yes, you are right. We've discussed it and decided to keep it like that till it is only one place. In the long run we should have different tsconfigs and call them depending on the env variables.

**Comment by hexa00** [comment]
Not sure I understand the different tsconfigs and env vars ?

**Comment by akosyakov** [comment]
tsconfig files support inheritance with overloads, so we could define one default `tsconfig.json` and one `dev.tsconfig.json` there we add `sourceRoot` property. 

For example, we could have `compile.js` script checking the presence of `buildServer` variable in the env vars and depend on it calls tsc with different tsconfig files, like `tsc -p dev.tsconfig.json`. Locally `buildServer` won't be present, travis build jobs could be configured to have it. In `package.json` we still will have only one script to build `node compile.js` instead of `tsc`. It could also be done somehow differently.

It seems to us like a lot of configurations right now, so we've decided to keep it simple.

**Comment by hexa00** [comment]
OK thanks for the explanations!

**Comment by hexa00** [comment]
Fixed by #166
