### ISSUE TITLE
What guideline should we follow when writing mocha tests

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#1353]
I was just wondering what's the appropriate way to use describe() and it() in our tests. To me it makes sense that the string in `describe()` should be the component/test/class being tested such as the `it()` after really specify something being tested for that particular component/test/class. i.e 
```
describe('SpecificService')
    it('should do X')
    it('returns Y when Z')
```
Mind you, most of the tests already present in theia follow this, so when running `yarn run test` you can quickly understand what the test does/maybe why it fails, which component/class/test is not behaving correctly etc. which is good. Some tests currently do not however (I think I've written some of them) and it doesn't really make sense when you look at the log of running the tests. We could even add a short desc in the coding guidelines for this maybe? WDYT

**Comment by akosyakov** [comment]
>  you can quickly understand what the test does/maybe why it fails, which component/class/test is not behaving correctly etc.

You can understand it only by reading a test code, debugging a test or if someone put an additional information in the failed expectation to capture the broken state. I don't think forcing such conventions is helpful. It adds the burden of enforcing them without the actual value.

**Comment by epatpol** [comment]
I still think that reading something like 
```
@theia/search-in-workspace:   ripgrep-search-in-workspace-server
@theia/search-in-workspace:     ✓ returns 7 results when searching for "carrot" (323ms)
```

makes more sense than 

```
@theia/core:   Path
@theia/core:     ✓ new from /foo/bar/file.txt
```

or

```
@theia/git:     exec
@theia/git:       ✓ version (140ms)
```

Note that maybe forcing it isn't the correct way to do it, and like I said it's not a really big issue, as I can only count the occurences of not very descriptive test cases on my fingers, but I do feel like the text should clearly and shortly describe what happens in it without looking at the code explicitly every time.

**Comment by akosyakov** [comment]
You are right, but all 3 examples above are fine. The second test tests a constructor with the given value, the third `exec` function of git with `version` argument. I can tell it from names. Actually, the first one is verbose and does not point to the method under test, but one still can derive `ripgrep-search-in-workspace-server.spec.ts` filename from it and then use text search to find the test.

I don't think to force everybody writing verbose test names confirming some format is necessary. What issue does it solve?

My guidelines are simple:
- **If one can find a test easily and code under test it is a good test name.** One can achieve it as simple as mention the test file name in the first `describe` and tested function/method in `it`.
- **When tests fail it should print failed expectations**, like expected 7 results but was 6 for "carrot".

And 6 is the real problem because one should debug a failed test to understand why and sometimes even to be able to see 6 if failed expectations are poor. It is not solvable by naming.

**Comment by epatpol** [comment]
Thank you for the points above. I do admit that for debugging it doesn't even matter that much as you will end up going direclty into the file/code anyway. I'm still not really sure about the cases above though, true the 2nd one can be deducted to be a new path from a specific string, but the 3rd one doesn't really shows what the test is doing apart from calling a method named version. Are you expecting a specific version string formatted differently, are you expecting it to return a string, or print the version etc. I agree that there is no need to be overly verbose, and mention all the context variables and everything in the string, but for consistency across the tests it makes sense to specify not calling the method, but what is expected from this `it`.

Not only that but by being verbose about what you expect in the behavior of a test, it's a lot faster to check if a test was already implemented for something, especially if you aren't the original author of the said code.

Anyway, I'll close this for now as it's not really an issue, but more of a discussion about best practices for mocha, and I think the guidelines you mentionned above should be good enough for most cases.
