### ISSUE TITLE
[keybinding] Left Arrow key not working in Git View comment field

### ISSUE THREAD

**Issue by geropl** [theia-ide/theia#1381]
Right arrow works fine and scrolls through the text as expected. Left arrow has no effect.

**Comment by epatpol** [comment]
Looking at the code I think keybindings for that might not be registered correctly? Or at least they're registered directly in widget.ts, which might be fine. Here I get the following error whenever KEY.ARROW_RIGHT is called though:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at GitWidget.GitBaseWidget.selectNextNode (git-base-widget.ts:148)
    at GitWidget.GitBaseWidget.handleRight (git-base-widget.ts:116)
    at git-base-widget.ts:105
    at HTMLDivElement.<anonymous> (widget.ts:108)
```

Which makes it seem like this.gitNodes is undefined. Because it throws an error, the following after `action()` is never called in `widget.ts`

```
        if (kc.equals(keyCode)) {
            action();
            e.stopPropagation();
            e.preventDefault();
        }
```
So there's two things wrong here, first there should be an undefined check when using the arrow keys in `git-base-widget.ts` and second, the key event listeners for the message box should not prevent the default execution of keys. I feel like there should be some sort of context for those keybindings, but because they're not registered with our registry I don't know how we should do that. Also isn't that a problem here that we add another key event listener here for those key events (on top of the one that already exists for keybindings) ? This makes it so that two handlers are called when pressing the arrow keys inside the git widget, i.e the one in `frontend-application.ts` and the one in `widget.ts`.

**Comment by epatpol** [comment]
I have no idea how to add a key listener to the VirtualElement "changesOuterContainer" under the git base widget one as it's not a widget.

**Comment by svenefftinge** [comment]
Also enter and key up, down don't work

**Comment by epatpol** [comment]
Note that I'm not technically working on that, I just wanted to test it out for myself and investigate a bit. So yea, the key down listener should be registered on the bottom part of the git container and not the whole thing, so that they don't override text boxes. Same reason why enter/key up don't work either.

**Comment by epatpol** [comment]
Nevermind let me push something and you guys can try and review
