### ISSUE TITLE
multiple Theia

### ISSUE THREAD

**Issue by jgroom33** [theia-ide/theia#1622]
I'd like to use a different base uri. (currently, only / appears supported without an extension)
Use case:
Assume the scenario where 2 instances of Theia are running on a docker host.
Container 1: 
* root.uri=/foo
* docker port mapping= x:3000

Container 2 
* root.uri=/bar
* docker port mapping= y:3000

Allowing a cli config parameter for root.uri would simplify host routing in some scenarios.

**Comment by marechal-p** [comment]
@marcdumais-work marking you because I was wondering how this would play out ?
How would the host know in which container to dispatch the HTTP request ?

Because this URI routing looks like something along URL Rewrite, where each running instance is still running with `/` as its root, but if requested URI on the docket host is `/foo` then remap to container 1.

(from the example, the two Theias are on different ports -x and y-, makes sense because I don;t think we could use the same ports on the same machine because docker. but because on both the exposed port is 3000, how do docker manage the request routing ?)

**Comment by marechal-p** [comment]
Looking at it a bit longer to understand the issue, it seems like the best thing to do is to setup a reverse proxy making the dispatch between the containers.

- [one StackOverflow take on the question](https://stackoverflow.com/a/30960011)
- [nginx remote proxying](https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/)

But there might be other technologies that achieve the same result.

**Comment by jgroom33** [comment]
Agree, the proxy could handle the routing:
host                docker
x.x.x.x/foo -> x.x.x.x:y
x.x.x.x/bar -> x.x.x.x:z

It would be beneficial to also allow setting the root path of each container.  This would simplify the nginx config (only port mapping would be necessary):
host                docker
x.x.x.x/foo -> x.x.x.x:y/foo
x.x.x.x/bar -> x.x.x.x:z/bar

**Comment by marechal-p** [comment]
```nginx
location /foo {
    proxy_pass http://a.b.c.d:xxxx/;
}

location /bar {
    proxy_pass http://a.b.c.d:yyyy/;
}
```

**Comment by svenefftinge** [comment]
> currently, only / appears supported without an extension

I don't think that is true. Can we close it?

**Comment by marechal-p** [comment]
@svenefftinge if it isn't true you should just point to a way to do it, because I was taking a look around, and I didn't find how to do it without altering the sources... I am also unable to find a good use case for changing Theia's root URI, as the previous one mentionned kind of adds a step that we could not take (just redirect to `/`).

**Comment by jgroom33** [comment]
I'm not opposed to closing this. As I agree, there are other ways to solve the problem.
At the same time, it is fairly common for services to allow changing their root.

**Comment by svenefftinge** [comment]
Sorry, I thought the issue was that Theia is expecting to run on `/` using absolutre pathes which it 
I don't see how adding a root property to Theia would help, because we still wouldn't be able to share the same port between multiple theia-instances. 
Instead, this should be done through reverse-proxying. (Please reopen if I missed something)
