### ISSUE TITLE
[Pop-up blocker] Opening another workspace does not work

### ISSUE THREAD

**Issue by spoenemann** [theia-ide/theia#1631]
File &rarr; Open &rarr; choose a workspace folder. With Safari browser the window is reloaded (see #981), but then the old workspace folder is still shown.

**Comment by AlexTugarev** [comment]
If new tab/window cannot be opened (e.g. because of a Pop-up blocker), should instead load the new workspace in same window? 

[`WorkspaceService`](https://github.com/theia-ide/theia/blob/master/packages/workspace/src/browser/workspace-service.ts#L67) will reset workspace root back to previous value on unload.
