### ISSUE TITLE
Basic Git Extension

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#165]
A git extension shall allow the user to interact with a git repository of the file system. The user should be able to perform the following git commands through a graphical user interface:

- fetch
- pull
- merge 
- commit 
- push

A dedicated git view will list all changed files in sections depending on whether they are staged or un-staged. Double-clicking a file entry will open a diff editor showing the changes. An action allows staging respectively un-staging the changes of a file. The diff editor allows to further modify the local file copy.

**Comment by hexa00** [comment]
Some suggestions about this, It would be nice to:

- Support rebasing by editing the rebase file from the editor (like if you would use EDITOR=theia with git CLI
- Support git annotate (blame) by showing the results in the editor

Also is it possible to use theia as an EDITOR ? so that git cli would open theia ?

**Comment by kittaakos** [comment]
> Some suggestions about this, It would be nice to:

Great idea! Please submit a new, separate issue for all the cool enhancements for the Git integration. We can collect your and other's ideas as well there, and we can spare this ticket for the basic support. Thank you!

**Comment by svenefftinge** [comment]
Fixed with #392
