### ISSUE TITLE
[monaco] ESC doesn't close completion widget

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1688]
The ESC key no longer closes the suggestion popups and hovers.

**Comment by AlexTugarev** [comment]
@kittaakos are you considering to change it so that the `esc` binding is registered here

https://github.com/theia-ide/theia/blob/aef8737c78bc499ae156e9837895ef7b0d0b4e04/packages/git/src/browser/blame/blame-contribution.ts#L92

and unregistered here

https://github.com/theia-ide/theia/blob/aef8737c78bc499ae156e9837895ef7b0d0b4e04/packages/git/src/browser/blame/blame-contribution.ts#L115

?

gitlens does something similar.

**Comment by kittaakos** [comment]
I would rather return with `false` from [here](https://github.com/theia-ide/theia/blob/aef8737c78bc499ae156e9837895ef7b0d0b4e04/packages/git/src/browser/blame/blame-contribution.ts#L68) if the `SuggestModel#state` is **not** `Idle` (the content assist is visible). Then I am planning to create a new keybinding context for the editors that is enabled **iff** `EditorTextFocusContext` is enabled and there is not content assist. At least, that is my plan so far.
