### ISSUE TITLE
Unable to scroll Git view's list of changed files

### ISSUE THREAD

**Issue by jopit** [theia-ide/theia#1767]
Running the browser-based version of Theia 0.3.8, I'm unable to scroll the list of changed files in the Git view.

**Comment by AlexTugarev** [comment]
I think this was resolved in GH-1746. I don't see this issue since then. Maybe @kittaakos can comment on this.

**Comment by kittaakos** [comment]
Well, I might have fixed it accidentally but was not intentional for sure. There was a problem with the parent container of the virtual widgets; I did some changes there. And yes, I have verified the scrolling, it worked on the branch. Could you please try it again with the HEAD of the `master`, @jopit? Thanks!

**Comment by jopit** [comment]
Scrolling is working when running from HEAD of master.
