### ISSUE TITLE
User-Configured Key Bindings

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#182]
- As an IDE user I want Theia to provide sane defaults bindings for the usual IDE commands, a way to remap them persistently and have the option to reset them to the default values.  
- As an extension developer I want a mechanism that enables my extensions to contribute key bindings.

**Comment by svenefftinge** [comment]
We have the second part already ([see](https://github.com/theia-ide/theia/blob/master/packages/editor/src/browser/editor-keybinding.ts))

This ticket should be about, allowing a user to override those keybindings in a configuration file (keymapping). 
In Theia a [keybinding](https://github.com/theia-ide/theia/blob/master/packages/core/src/common/keybinding.ts#L15) consists of a `keycode` a `commandid` and a `keybindingcontext`. The latter is a function, that when evaluated tells if a keybinding is enabled in the current context. It is similar to the `when` context in vs code. It also has an ID, which should be used in the keymap files, instead of a function (obviously).

**Comment by epatpol** [comment]
Thanks for the comments @svenefftinge,

I saw that the second part is already implemented. I was thinking about adding a keybindingprefservice (name subject to change) that would listen to the keybindings.json located in one's home directory (reusing what was done in the preferences). The format would be 
```
{
"command id": "custom keybinding",
...
}
```
There's just something that I'm not sure how to do right now, I noticed that the keybinding registry only has a `registerKeybinding` method that accepts a `Keybinding`. From what I understand this is a structure that you create with the help of Keycode.createKeyCode(). I'm not sure how I can create the same structure with a string i.e in the json file, the custom keybinding would be "M1+M2+W" for instance, instead of 
`                keyCode: KeyCode.createKeyCode({ first: Key.KEY_W, modifiers: [Modifier.M2, Modifier.M3] })
`
I guess I would need a parser from string (from my keybindings.json) to `Keystroke`, and then I could use Keycode.createKeyCode(). 

WDYT?

**Comment by svenefftinge** [comment]
Yes, something like that. 
In addition, also the keybinding context id should be included in the json file.

**Comment by svenefftinge** [comment]
See https://github.com/theia-ide/theia/blob/master/packages/core/src/common/keybinding.ts#L35

**Comment by akosyakov** [comment]
It would be nice if in API we also use 'M1+M2+W' for `keyCode` instead of `keyCode: KeyCode.createKeyCode({ first: Key.KEY_W, modifiers: [Modifier.M2, Modifier.M3] })`.

**Comment by akosyakov** [comment]
regarindg:
```json
{
"command id": "custom keybinding",
...
}
```
`command id` - spaces in JSON property names is not nice, you want to map it to TS interface.

We can follow VScode format:
```json
{
  "key": "M1+M2+W",
  "command": "say.hello", // command id
  "args": { "to": "World"  }, // command args, optional
  "when": "editorOpened" // context name, optional
}
```

**Comment by epatpol** [comment]
> It would be nice if in API we also use 'M1+M2+W' for keyCode instead of keyCode: KeyCode.createKeyCode({ first: Key.KEY_W, modifiers: [Modifier.M2, Modifier.M3] }).

Exactly, that's what I noticed when investigating that a bit, the API would need to be changed a bit to be easier to use IMO.

**Comment by svenefftinge** [comment]
The Context (KeybindingContext) currently doesn't work at all, since we just go over all bindings and take the first that is enabled. But the context should allow to override a certain "more global" keybinding with one in a more narrow context.

We can either do it like vs code, and come up with contexts that are hierarchical or we simply use a `priority :number` on the keybinding to indicate its importance. Looking at vs code I don't see too many use cases for overriding keybinding. UX wise it often is a bad idea anyway, especially for common keybindings.

**Comment by epatpol** [comment]
Can we close this? Or 

>and have the option to reset them to the default values.

We don't really have that? We would need a custom view with a maybe right-click -> reset key binding just like vscode.
