### ISSUE TITLE
messages / user notifications

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#185]
Messages are user notifications that can be triggered by Theia or its extensions.
The way they are showed to the user is configurable such that:
- A overlaying pop-up, that can display any HTML is shown with the following options :
  - A button to dismiss the information, 
  - An optional button for executing some action shall be provided.

- A messages are sent to a message view. This would be a bit like android notifications, allowing tasks in progress to be shown dynamically. This would also show notifications to the user that do not require an action from them.

Don’t show Again Option:
The user notifications system shall allow users to ignore particular notifications. Which messages are to be ignored shall be stored locally using the storage service (see §7).
~~View for IDE messages, like Debug info or error messages of the IDE.~~(see #786)

Integrate with the Language Server Protocol:
The LSP defines `showMessage` notifications and requests, which shall be implemented on the client using the previously described user notifications service.

**Comment by akosyakov** [comment]
- [ ] [IMessageService](https://github.com/Microsoft/vscode/blob/d30825f323a7f77e17d25b212fef6440e73fdc14/src/vs/platform/message/common/message.ts#L34) for Monaco should be implemented with Theia message service, at the time messages from Monaco are logged to the console.

**Comment by svenefftinge** [comment]
> View for IDE messages, like Debug info or error messages of the IDE.

I opened  #786 as this is unrelated to the notifications.

**Comment by svenefftinge** [comment]
Also related : https://atom.io/docs/api/v1.21.2/NotificationManager

**Comment by akosyakov** [comment]
The approach from https://github.com/theia-ide/theia/issues/185#issue-234907378 does not fit with the LSP:
- a notification should support multiple actions, not one.
- a notification is static, it cannot be updated dynamically, e.g. to display progress. It is better to display progress with something like `Output View` in VS code.
- `Don't show again` is implemented by the client since there is no generic way to identify a message kind, e.g. a language server sends a message with `Don't show again` action and if this action is chosen by a user then it is up to the server how to preserve the information. Some clients can use the local storage for it.

**Comment by marcdumais-work** [comment]
Thanks @AlexTugarev . I think this is completed. Else please re-open
