### ISSUE TITLE
[build] master branch not properly published

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#1856]
The publishing of `next` versions fails : https://travis-ci.org/theia-ide/theia/jobs/375064059

As a result, only `core` is published, which makes it impossible to use the `next` tag atm.

**Comment by marcdumais-work** [comment]
Looks like it was a glitch? The next one published as expected: https://travis-ci.org/theia-ide/theia/jobs/375515932

**Comment by marcdumais-work** [comment]
Looks like this issue is back:
https://travis-ci.org/theia-ide/theia/jobs/376816452

**Comment by svenefftinge** [comment]
can we close?

**Comment by svenefftinge** [comment]
@marcdumais-work the publishing is again failing. 
It seems like your logging change didn’t make it on the master. Is there a reason?

**Comment by svenefftinge** [comment]
I just saw https://github.com/theia-ide/theia/pull/1898#issuecomment-388807585
Which says, that the flag is not working.

**Comment by marcdumais-work** [comment]
Yes, it was a theory that adding the flag might give more information about the reason for the failure, but if 
it's really the case is unknown, since I can't reproduce the failure using a private registry. 

It's one of those situation when a leap of faith is required - we need to merge the change, before we can find out if it will help.
