### ISSUE TITLE
Prevent history back and forth on scrolling sideways

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#1860]
It triggers navigation back in the browser. According to [this issue](https://github.com/Microsoft/monaco-editor/issues/750#issuecomment-382725494) it should be fixed in Theia.

**Comment by spoenemann** [comment]
Here are my findings so far:

 * Navigation can be suppressed by calling `event.preventDefault()` on `'wheel'` events.
 * This has the side effect that scrolling does not work anymore for containers with native scrolling.
 * As far as I have learned, the only way to detect whether there is a child container with native scrolling enabled is to walk through the parent hierarchy of the `event.target` and check for `scrollTop` / `scrollLeft` properties. In perfect-scrollbar this is done with the `shouldBeConsumedByChild` function here: https://github.com/utatti/perfect-scrollbar/blob/master/src/handlers/mouse-wheel.js
 * An additional side effect is that scrolling does not work anymore for Monaco editors with Firefox.
 * You can use https://jsfiddle.net/spoenemann/wzr1ct45/3/ to experiment.

I could think of two solutions:

 1. If the system is OS X and the browser is not Firefox, add a `'wheel'` event handler to `document.body` that checks whether the event should be consumed by a child container, and if not prevents the default.
 2.  If the system is OS X and the browser is not Firefox, add a `'wheel'` event handler to `document.body` that always prevents the default.

I believe 1. is quite problematic since it could affect performance. On the other hand, 2. means that native scrolling does not work anymore, so everyone has to use perfect-scrollbar to enable scrolling.

What do you think?

**Comment by spoenemann** [comment]
Maybe solution 1 is not that bad because it applies only in cases where scrolling is not already done by perfect-scrollbar or monaco (which do `stopPropagation()` when they scroll). I'll give it a try.
