### ISSUE TITLE
[Question] How to download files from develop workspace?

### ISSUE THREAD

**Issue by huyuwen** [theia-ide/theia#1874]
Drag & Drop has been supported to upload files and folders from local filesystem to remote workspace.
But it seems user can't download or save some files or folders from remote workspace to local filesystem.

Or did I miss some feature in theia?

**Comment by kittaakos** [comment]
@huyuwen, as far as I know, we do not yet have such a feature in Theia.

CC: @lmcbout

**Comment by lmcbout** [comment]
Right now, Drag & Drop use remote  to local filesystem only

**Comment by huyuwen** [comment]
Well then, do you have any recommend approaches to fetch file from remote workspace to local filesystem (where we launch web browser)?

**Comment by epatpol** [comment]
This would be a nice feature, we would need to discuss what's the best way to implement it beforehand however. I.e would right-click -> Download be good enough? Supporting drag and drop from theia to outside OS might be too complicated for now, so that's what I would suggest. Kinda like how Google Drive does it (If you multi select stuff you would get a zip file containing the files). WDYT? Also maybe this should be discussed in another issue altogether (if one isn't already opened).

**Comment by kittaakos** [comment]
Alternatively, you could implement your custom backend contribution, and create a REST endpoint, that you can you to download the resources. Something similar we did for the [HTML/SVG previewer](https://github.com/theia-ide/theia/blob/c3a014760e639b676587841245866c35e8137566/packages/mini-browser/src/node/mini-browser-endpoint.ts#L79). But instead of sending back the text or binary content to the frontend, you would [need to download](https://expressjs.com/en/api.html#res.download) your files. Keep in mind; you'll have to [map the file URIs](https://github.com/theia-ide/theia/blob/c3a014760e639b676587841245866c35e8137566/packages/mini-browser/src/browser/location-mapper-service.ts#L120) to the appropriate endpoint URLs. I hope this helps.

Feel free creating a follow-up task for the corresponding feature request. Also, we accept PRs :)
