### ISSUE TITLE
[keybinding] `Alt+Shift+W` closes all tabs not just the editors

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#1999]
The current behavior does not make any sense, and it is clearly a regression compared to the previous one. It should close all the open editors but not evrything. Closing everything is useless.
![screencast 2018-05-30 13-12-57](https://user-images.githubusercontent.com/1405703/40717131-93b9980c-640b-11e8-914d-427b3776853f.gif)

**Comment by spoenemann** [comment]
Like Alt + W (close single tab), Alt + Shift + W refers to the currently active tab bar. So if you have selected a widget from the side bar, Alt + W will close that widget and Alt + Shift + W will close all widgets from that side bar.

What do you propose exactly? Alt + Shift + W should close all widgets in the main area instead of the currently active tab bar?

**Comment by kittaakos** [comment]
> What do you propose exactly?

Alt+Shift+W should close everything in the main area. This is what I would expect as a user.

**Comment by kittaakos** [comment]
I have just checked the behavior in Eclipse. I personally like that better than my previous proposal, I just do not know whether we can do that. Alt+Shift+W closes all the editors in the application.

Before Alt+Shift+W
![theia-sadl - org eclipse lsp4j position - eclipse sdk 2018-06-01 10-10-57](https://user-images.githubusercontent.com/1405703/40829648-5d6e8904-6584-11e8-8ab2-af545e97aac3.png)


After Alt+Shift+W
![theia-sadl - eclipse sdk 2018-06-01 10-11-17](https://user-images.githubusercontent.com/1405703/40829643-57ab48ea-6584-11e8-8ff4-f9e01ca97abb.png)
