### ISSUE TITLE
[suggestion][navigator] Be able to see the filename in the navigator view when there is a long path

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2010]
Currently, I cannot see the full path+ filename unless I make the navigator section wider. Can we have either an horizontal bar or may be a tooltip when navigating over a file showing the path: path + filename, so we don't need to make the navigator view wider and take the estate of the editor!
 In eclipse, there is an horizontal scroll bar for the package and the project view.

**Comment by kittaakos** [comment]
> tooltip

+1

> navigating over

What does that exactly mean? Did you mean you have the selection on a node and you use the cursor arrows to traverse the navigator,  just clicking around in the navigator?

> path + filename

 - Out of curiosity, why do you need the path? Do you want to copy-paste it or just see something better in the navigator? Could you attach one or two screenshots how do the default layout and the navigator look like in your browser? Maybe some info on your screen resolution would be beneficial too.
 - AFAIK, we represent URIs on the UI instead of paths. Just imagine, you are on Windows and you get back the Linux FS path, what can you do with that? Or did you mean WS relative paths?

> horizontal scroll bar

I am not against a horizontal scrollbar but I am positive there was a good reason we do not have it yet. VS Code does not have it either. [CC: @akosyakov]

**Comment by kittaakos** [comment]
Eclipse does this:
![screencast 2018-06-01 22-10-07](https://user-images.githubusercontent.com/1405703/40861321-ebc08720-65e8-11e8-9714-a2d2933d7df7.gif)

The tooltip perfectly overlays the label in the tree viewers.

(Note: the app I have used to record the gif removed the mouse cursor; of course it was there.)

**Comment by lmcbout** [comment]
I don't know which version of eclipse you use, my eclipse version has no tooltip over the file name, but this is exactly what I would like to have in Theia, be able to see the filename when hovering.

**Comment by lmcbout** [comment]
Also, make sure to have a tooltip showing the full path when hovering the root folder
