### ISSUE TITLE
Searching should be allowed for opened editors despite if a workspace is present or not

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#2298]
Theia should allow searching (`Search Widget`) for all active opened editors despite if a workspace is currently present or not. Currently Theia does not allow searching if a workspace is not present. 

Essentially, Theia should cover the following use cases:
1. **Workspace Present** 🡒 Searching is performed in the context of the workspace including sub-folders and sub-workspaces. 
2. **No Workspace Present, Files Opened** 🡒 Searching is performed on all active opened editors
3. **No Workspace Present, No Files Opened** 🡒 A message should be displayed to users indicating _Searching is only allowed for open workspaces or files_

![editor-crash](https://user-images.githubusercontent.com/40359487/42381693-e479ebe6-80ff-11e8-8b71-24dddaca6c5c.gif)
Example of incorrect behavior in Theia's search despite open file.

**Comment by marcdumais-work** [comment]
This would be the equivalent of having a virtual dynamic workspace, composed of the opened files, for the purpose of "search in workspace". It might possibly be nice to have, but I think it's probably overkill ATM, and if we want such a thing, might be better handled in a generic way so that other extensions can also use that virtual workspace. 

Personally I think we already have workspaces and should use them if we want their features.
