### ISSUE TITLE
[react] don't reexport react widgets

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#2314]
We should make sure that react widgets are not re-exported, otherwise it enforces usage of react and does not allow alternative implementations of JSX.

For example, the status bar widget should be extracted from https://github.com/theia-ide/theia/blob/master/packages/core/src/browser/status-bar/status-bar.tsx, that it does not get reexported whenever someone is using the statur bar API.

**Comment by svenefftinge** [comment]
Given that we have migrated all the widgets is it realistic, that someone could use Theia without a react dependency?

**Comment by JanKoehnlein** [comment]
We suspected that this was the cause of compile errors with Theia extensions using sprotty.
After migrating Sprotty to use locally defines JSX factories for the virtual DOM part (snabbdom) we still had errors about duplicate global typings for the virtual HTML elements. It turned out that for packages using multiple JSX factories, we have to disable lib checks using `"skipLibCheck": true` in the tsconfig. Interestingly, VSCode seems to check local `*.d.ts` files despite that setting while the command line compiler doesn't. Anyway, this workaround allows using Theia with other VDOM frameworks anymore.

See https://github.com/theia-ide/sprotty/issues/203

I think this issue can be can be closed without further action.
