### ISSUE TITLE
Missing HTML Syntax Highlighting

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia#2354]
prior to #2306 - HTML seems to have missing Syntax Highlighting.

![image](https://user-images.githubusercontent.com/14976516/42634483-ec7f8f9c-8615-11e8-9938-d31a22ea7b7c.png)

JSON Manifest for my app 
```json

{
    "private": true,
    "dependencies": {
       "@theia/core": "next",
       "@theia/filesystem": "next",
       "@theia/workspace": "next",
       "@theia/preferences": "next",
       "@theia/navigator": "next",
       "@theia/process": "next",
       "@theia/terminal": "next",
       "@theia/file-search": "next",
       "@theia/messages": "next",
       "@theia/git": "next",
       "@theia/editor": "next",
       "@theia/languages": "next",
       "@theia/markers": "next",
       "@theia/monaco": "next",
       "@theia/typescript": "next",
       "@theia/json": "next",
       "@theia/textmate-grammars": "next",
       "@theia/java" : "next",
       "@theia/cpp": "next"
    },
    "devDependencies": {
        "@theia/cli": "next"
    },
    "theia": {
        "target": "browser"
    }
}
```

**Comment by akosyakov** [comment]
I was able to reproduce it. The issue is that we bogusly assume that language id is its index among languages:
<img width="1637" alt="screen shot 2018-07-14 at 21 57 13" src="https://user-images.githubusercontent.com/3082655/42727997-039fd7b2-87b1-11e8-837e-daed2ff243a5.png">
 
You can see, that language index is 10, but id is 11. I will open a PR to rely on internal VS Code apis to get an id.
