### ISSUE TITLE
Creating a new file shouldn't open *.md files in the preview mode

### ISSUE THREAD

**Issue by orucky** [theia-ide/theia#2462]
When a new file is created, the same rule is followed for the *.md files as if an already existing file is double-clicked on to view/edit - a preview is opened instead of the editor. That means the standard workflow is now create a new file -> double click on an empty preview (after understanding it's a preview, not an editor, and thus the keys pressed don't show up) -> get to the editor. I find this very unintuitive.

I suggest that for a new file of any kind the editor is always started (there is no other way to populate the file other than to get to the editor and type something anyway); let's leave the existing preview/editor opening policy only for the already existing (or maybe better, *nonempty*) files only.

**Comment by vince-fugnitto** [comment]
Closing the issue since it is quite old.
We do have the preference `preview.openByDefault` which controls whether open the preview instead of the editor by default. I believe this preference would be enough to handle multiple use cases.

There has been a lot of work improving Theia as a whole, and quickly testing the implementation, I don't see any obvious flaws to Theia's behavior.
