### ISSUE TITLE
Recommended way to get the path of the current working directory

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#2560]
Is there a recommended way to get the current working directory? Are there differences in getting the current working directory from the Node side or the browser side?

Also, is there a way to set the working directory from within the code?

**Comment by akosyakov** [comment]
> Is there a recommended way to get the current working directory? Are there differences in getting the current working directory from the Node side or the browser side?

Since the backend is not aware of the user session, only the frontend, it is better to manage the workspace on the frontend. There is a frontend service for it: https://github.com/theia-ide/theia/blob/master/packages/workspace/src/browser/workspace-service.ts

> Also, is there a way to set the working directory from within the code?

https://github.com/theia-ide/theia/blob/e90265d3b70936ac2182c293701d2a11a1d8a981/packages/workspace/src/browser/workspace-service.ts#L209-L214
