### ISSUE TITLE
Typescript 3.x drop support for WebKit* Types

### ISSUE THREAD

**Issue by eneufeld** [theia-ide/theia#2682]
The File-tree-model is using WebKitEntry, WebKitFileEntry and WebKitDirectoryEntry eg https://github.com/theia-ide/theia/blob/d656a7abfc42346a4080e7f8665a7b42bf6fc7db/packages/filesystem/src/browser/file-tree/file-tree-model.ts#L181.
This is not compatible with Typescript 3.x as they removed WebKit* types see https://github.com/Microsoft/TypeScript/issues/25515#issuecomment-403897228
So instead of WebKitEntry etc FileSystemEntry etc from the File API should be used (https://developer.mozilla.org/en-US/docs/Web/API/FileSystemEntry) .

**Comment by AlexTugarev** [comment]
@akosyakov already start working on that in https://github.com/theia-ide/theia/pull/2563

**Comment by akosyakov** [comment]
We can extract this part from #2563 and migrate to TS 3 without project references for now.

@eneufeld I will look again, but I've not seen `FileSystemEntry` in new `lib.d.ts`. I don't want to rewrite the code against another API, since it does work and I was not able to find the complete standard equivalent, so just copying WebKit typings for now.

**Comment by eneufeld** [comment]
All solutions would be fine for me, right now I set the typescript version to 2.9.2 so I just wanted to report the error, so that others don't run in the same issues as I did
