### ISSUE TITLE
[Problem View] Options to expand/collapse the tree items

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2789]
Should we implement an option to expand/collapse all the tree items  in the problem view .
Currently, the  option from the title bar of the Problem view, there is an option "Collapse", but this seems to only close the problem view, not collapsing the tree inside the problem view.

**Comment by vince-fugnitto** [comment]
@lmcbout 
I do believe `collapseAll` would be useful for end-users navigating through the `problems-view` but I'm not convinced about `expandAll`. This could potentially be problematic for when there are a large number of markers. Also, navigation is much easier with collapsed nodes rather than expanded nodes.

What are your thoughts?

**Comment by lmcbout** [comment]
@vince-fugnitto For this issue, we can just add "Collapse all" in the context menu and on the menu bar. The other two commands , we can create a new issue for it.

collapse all
collapse all starting at the selected item (only collapse the items under that tree )
expand all starting at the selected tree item (Only expand all items starting from the selected tree item)
