### ISSUE TITLE
[Problem view]  Should we implement a context menu in the problem view !

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#2790]
Suggestion: Why not having a context menu in the problem view for:
- Filter errors/warnings....
- Have a search options
- Expand /collapse all
- Copy the error message 
- Select all 
- Show in Navigator

**Comment by vince-fugnitto** [comment]
I think the issue should be broken down by each feature since a lot of them are addressed already:
- [ ] filter/search toolbar item https://github.com/theia-ide/theia/issues/5135
- [x] expand / collapse all
- [x] copy & copy message
- [ ] ~Select All~ (not sure it really applies to the problems view)
- [ ] ~Show in Navigator~ (doesn't apply, selecting a problem marker will already open the editor and thus highlight the explorer)

Since there is only one feature that really needs to be addressed (`filter/search`) and there is an issue for it, I'll close this one.
