### ISSUE TITLE
Task menu entry in Theia

### ISSUE THREAD

**Issue by jeanlucburot** [theia-ide/theia#2889]
Is there any description on what to do and how to use the Task menu entry in the main menu? It has the two entries of `Run...` and `Attach...`. So I assume that I can only run tasks that I have previously attached, right? Also, what is a task? Is it a shell script located somewhere on the server side of the application that I can run from the front end? Is this Menu entry related or connected to the `@theia/task` [Task Extension](https://www.npmjs.com/package/@theia/task)?

**Comment by marcdumais-work** [comment]
Yes, these are from ```@theia/task```. The ```Run...``` entry triggers the quick-open menu, but since there are no defined tasks, there is nothing to select. 

_Attach_ is for  the case where you have multiple clients using the same Theia backend and same workspace, and want more than one to see the output of a running task. Start one or more long-lasting task, started in one client, and trigger _Task -> Attach_ in another client. You'll be shown a list of tasks currently running in the backend, and be permitted to select any to attach-to. When attaching, a new terminal widget is created and the output of the task is displayed in it. 

Tasks can be anything that can execute on the platform where the Theia backend runs. For example, on Windows, a ```.bat``` or ```.exe``` file can be executed as a task. 

Theia's tasks can be defined in ```[workspace | user_home] /.theia/tasks.json```

If you have Theia's source code around, there is an example, used in the unit tests: https://github.com/theia-ide/theia/blob/master/packages/task/src/node/test-resources/.theia/tasks.json

You can try it  by using folder ```<theia src root>/packages/task/src/node/test-resources/ ``` as workspace
e.g.:
``` 
cd <theia src root>/example/browser
yarn start ../../packages/task/src/node/test-resources/ 
```

Alternatively you can also define tasks programmatically, by contributing them through the ```TaskContribution``` Contribution Point. 

See the [README](https://github.com/theia-ide/theia/blob/master/packages/task/README.md) for more details.
