### ISSUE TITLE
Add MS Debug Adapter as a jdt.ls Extension

### ISSUE THREAD

**Issue by tsmaeder** [theia-ide/theia#3058]
We should make an extension that contributes Microsofts debug adapter as an extension to jdt.ls in Theia. This would involve including the appropriate bundles (or downloading them, as with jdt.ls) and contributing them via the existing extension point.

**Comment by tsmaeder** [comment]
See also https://github.com/eclipse/che/issues/10079

**Comment by tsmaeder** [comment]
The current idea is to port the code from vscode-java to pick up jdt.ls extensions from vscode plugins and use the microsoft plugin directly.

**Comment by svor** [comment]
> The current idea is to port the code from vscode-java to pick up jdt.ls extensions from vscode plugins and use the microsoft plugin directly.

As it was discussed with @tsmaeder and @benoitf 
The way to port the code from **vscode-java** extension to **theia-java** extension and use microsoft plugin directly won't work. Because there are two problems:
1. There is no way to read theia-plugins configurations from the theia-extension (java-extension) to pick up jdt.ls bundles (Plugin API can't be used from Theia extensions).
2. We can't use vscode java-debug plugin directly because it depends on vscode java plugin and it gets some information from it for example the value of [JAVA_HOME](https://github.com/Microsoft/vscode-java-debug/blob/c080a0d27533cfc2e4998fc4a6a59dc503afb89e/src/utility.ts#L114)
