### ISSUE TITLE
[mini-browser] Open URL?

### ISSUE THREAD

**Issue by adrienrenaud** [theia-ide/theia#3169]
Can I open an URL in mini-browser and not only a file?

**Comment by kittaakos** [comment]
@adrienrenaud, did you mean opening a blank mini-browser with an "editable" address bar and navigating to, for example, https://github.com? No, we do not (yet) support it. What would be your use-case?

**Comment by adrienrenaud** [comment]
@kittaakos, yes that's it. The use-case I had in mind was to open a jupyter notebook. Of course built-in (python) notebooks in Theia would be more attractive.

**Comment by kittaakos** [comment]
I see your point. Unfortunately, an `iframe` inside Theia acts as a black box. Due to security issues when interacting cross-domains, it is almost impossible to load a web page as is.

Here are a few issues:
 - When setting `src` to `https://github.com` you get an `Refused to display 'https://github.com/' in a frame because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".` error.
 - We cannot use `window.history` for navigation.
 - We cannot check the current location inside an `iframe`. `location.href` does not work.
 - We cannot access `frame.contentDocument.contentWindow.document`.
 - We cannot track the mouse cursor inside an `iframe`.
 - ...

We have decided to disable this functionality.

Unless you are willing to help us with a contribution, I have to close this task.

Feel free to ask if you have questions.

**Comment by kittaakos** [comment]
@adrienrenaud, this functionality is now available from the *Command Palette*:
 - Open the *Command Palette* with <kbd>Ctrl/Cmd</kbd>+<kbd>Shift</kbd>+<kbd>P</kbd>.
 - Type `Open URL` and hit *Enter*.
 - Type the URL.

From here: https://github.com/theia-ide/theia/pull/4357#discussion_r257585428
