### ISSUE TITLE
[keybindings] Edit keybindings report error when there is none.

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3209]
Open the keybindings UI, modify the command "close all" with a new keybindings "alt+shift+e"
Re-open the edit dalog and then, you get an error "keybindings currently collides".
This should not be an error here, you just define a new key for this command. Now In the edit dialog, change the key to use another key used by another command,  i.e. "alt+shift+c"  
This is a duplicate of another key bindings, but it does not report an error ,

**Comment by vince-fugnitto** [comment]
@lmcbout I've created two issues in order to break down the bug you reported. 
#3211 will handle not displaying a message whenever an update has yet to be performed.
#3212 will handle displaying the scope so that the second error you reported is more transparent to users. This occurs whenever a keybinding that overrides the default one from Theia (shadow) is created.

**Comment by vince-fugnitto** [comment]
closing based on #3211 #3212

**Comment by vince-fugnitto** [comment]
closing based on #3211 #3212
