### ISSUE TITLE
[keybindings][electron]Commands not shown in the key bindings widget

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3249]
In Electron, we have the following command which is not shown in the command pallet: "ctrl+k ctrl+o"
Need the issue #3173 to have the definition of this command

**Comment by vince-fugnitto** [comment]
@lmcbout I'm confused by your title and content, do you mean it does not appear in the `keybindings-widget` or in the command palette ?

**Comment by lmcbout** [comment]
@vince-fugnitto I change the title to be keybindings widget

**Comment by vince-fugnitto** [comment]
@lmcbout Sorry but unfortunately I'm still confused, your title states commands not shown in the `keybindings-widget` but the content of the issue refers to the `command palette`.

**Comment by vince-fugnitto** [comment]
@lmcbout the reason why the commands are not shown in the `keybindings-widget` is that they are not found in the `command-palette` for Electron due to some limitations for both Windows and Linux. The commands are explicitly not shown due to this reason. 

https://github.com/theia-ide/theia/blob/342187fe24775b82344ebcd350da72178aa39dfc/packages/workspace/src/browser/workspace-commands.ts#L46

https://github.com/theia-ide/theia/blob/342187fe24775b82344ebcd350da72178aa39dfc/packages/workspace/src/browser/workspace-commands.ts#L53
