### ISSUE TITLE
How can I add an extension to the e.g. browser example?

### ISSUE THREAD

**Issue by UdoW** [theia-ide/theia#359]
I want to add an extension to Theia and do not find any documentation on how to do it.

There are some questions to this:

- Where and how should I start? 
- How is the directory layout to be used?
- How can I develop locally?
- What development tools do I need if any?
- How to packetize my extension?
- How to deploy my extension in another Theia installation?

**Comment by akosyakov** [comment]
Please have a look at doc directory, it contains architecture and development documentation plus at README in generator-theia. It should cover first 4 questions.

Last 2 questions are work in progress. An idea that you will publish a node package to npm with a special keyword, by default `theia-extension`, and special property `theiaExtensions` pointing to entry modules. Such package can be installed as a dependency to the app by declaring in `theia.package.json`. Then you will use generator-theia to generate entry js scripts based on information from `theia.package.json` and extension packages.

**Comment by akosyakov** [comment]
Also have a look at yangster: https://github.com/yang-tools/yangster?files=1. It adds [a new extension](https://github.com/yang-tools/yangster/blob/master/theia-yang-extension/package.json) and use it in [a browser app](https://github.com/yang-tools/yangster/blob/master/yangster-app/theia.package.json) together with other theia extensions. For local node resolution you should provide a yo config as [here](https://github.com/yang-tools/yangster/blob/master/yangster-app/.yo-rc.json).

**Comment by UdoW** [comment]
Hmm, I am a beginner in everything here and I do not understand how the files in the doc folder could help me to get started. Sorry, the doc files are for real experts only.

**Comment by akosyakov** [comment]
> Where and how should I start?

You should follow [Developing docs](https://github.com/theia-ide/theia/blob/master/doc/Developing.md) to get started. Please ask concrete questions about individual steps in this document if something is not clear.

> How is the directory layout to be used?

The repo has multiple packages:
- generator-theia is [yo generator](http://yeoman.io/) for theia based apps
- `packages` folder contains core package and extensions to it
- `examples` folder contains example apps using core package and extensions
- the root package is wiring everything together with [lerna](https://lernajs.io/)

When you call `yarn`:
- lerna and yo are installed because they are dev dependencies in the root package.json
- when `prepare` script is executed which:
  - use lerna to bootstrap `generator-theia` and link it in root node_modules
  - use `generator-theia` to generate package.json for extensions and examples
  - use lerna to bootstrap extensions and examples
  - use lerna to run `clean` and `build` scripts on extensions and examples

> How can I develop locally?

Do you mean in Theia repo or you want to set up your project?

For the first [Developing docs](https://github.com/theia-ide/theia/blob/master/doc/Developing.md) explains how to build packages, including incremental builds, start applications, debug them and so on. If you have troubles with this document please ask concrete questions about individual steps.

For the second look at [yangster](https://github.com/yang-tools/yangster).

> What development tools do I need if any?

You should have proficiency in the following: 
- typescript, dom, node, electron, npm/yarn, inversify - for extension development
- lerna - for multi package development
- yeoman -  for generating apps

> How to packetize my extension?

A plain node package with `theia-extension` keyword and `theiaExtensions` property as [here](https://github.com/theia-ide/theia/blob/master/packages/filesystem/extension.package.json#L23). Read more about `theiaExtensions` [here](https://github.com/theia-ide/theia/blob/master/generator-theia/README.md#providing-extensions).

In Theia we generate `package.json` for extensions from `extension.package.json` to merge common dev dependencies, scripts, fields. For a single custom extension, you don't need it.

> How to deploy my extension in another Theia installation?

It should be enough to add a node package declaring `theiaExtension` as a dependency to `theia.package.json` and then run `yo theia:browser --force` or `yo theia:electron --force`. Explained [here](https://github.com/theia-ide/theia/blob/master/generator-theia/README.md#consuming-extensions).

**Comment by epatpol** [comment]
@UdoW as theia is still in its early stages a lot of documentation is still to be written (add that to the fact that everything is moving/updating quickly), so looking at the existing code is the best way to contribute something yourself. The current documentation should help you but I don't think it's currently in a state where it's the best entry point for getting into theia.

If you need help/have more specific questions I strongly suggest you come ask directly on the gitter channel [here](https://gitter.im/theia-ide/theia). Most likely someone there online can help you or point you in the right direction :)

**Comment by akosyakov** [comment]
@UdoW We have the documentation now on the authoring extensions: https://github.com/theia-ide/theia/blob/master/doc/Authoring_Extensions.md

As well as the example more complicated example: https://github.com/theia-ide/theia-extension-example

Have you checked it out? Could this issue be closed?

**Comment by marcdumais-work** [comment]
@UdoW Closing this issue. Please re-open if you still have questions.
