### ISSUE TITLE
[performance] [filesystem] Slow loading with large workspace root

### ISSUE THREAD

**Issue by caseyflynn-google** [theia-ide/theia#3697]
Theia takes an exceptionally long time starting when using a large directory as the workspace root. AFICT the issue started to manifest after the submission of https://github.com/theia-ide/theia/commit/543b119a32652f662968411370979ea002a1736a

**Comment by NeekSandhu** [comment]
I'm not sure if your issue is what I think your issue is. But I was browsing through source files of theia to get some inspiration on implementing a file tree. To my surprise I was pretty surprised when I saw this:

https://github.com/theia-ide/theia/blob/b265e061861779a7e9fdbf908e4886b875b9ac4b/packages/core/src/browser/tree/tree-widget.tsx#L185-L211

I think iterating (top-down) over __entire__ tree model per __one__ change is pretty expensive IMO. Expensive especially when computing nodes that `react-virtualized` won't ask for anyway, since those are out of the viewport.

I'm just a few hours away from publishing my file-tree implentation with `react-virtualized` that doesn't maintain a top-down flattened structure, instead it computes node for given index on-demand and lazily. Compared with current theia implentation, the number of recursions are exactly same, the only difference is that theia computes flattened structure all at once as opposed to lazy/deffered on-demand (when asked by `react-vitualized`)

Here's a laymans version of the data structure I'm using:

```typescript
interface IFileEntry {
  fileName: string
  id: number
}

interface IDirectory extends IFileEntry {
  /**
   * Σ children.length of self plus IDirectory.branchSize of all (expanded/visible) leaves
   */
  branchSize: number
  children: Array<IFileEntry | IDirectory>
} 
```

Now that's an oversimplification. There's a lot more in reality like using caches with binary search and stuff.

Let me know if you guys are interested!

**Comment by akosyakov** [comment]
@caseyflynn-google is it because of `--no-cluster` mode? fs/git repos watching takes long and blocking the backend? Could you try without?

@NeekSandhu I don't think it is about rendering. The file tree is never loaded completely, but lazily, so only traversed part is flatten. Changes are debounced to avoid flattening of rows on each change. We have not seen this part as the hot spot during profiling sessions even for big folders, like node_modules, and have not tried to optimize because of it. Anyway if you can optimize it without breaking APIs and behavior, your changes would be very welcomed! Please bring reproducible numbers showing improvements.

**Comment by caseyflynn-google** [comment]
https://github.com/theia-ide/theia/pull/3699
