### ISSUE TITLE
Remove usage of unsupported language features

### ISSUE THREAD

**Issue by thegecko** [theia-ide/theia#3730]
As discussed in #3693 and in the dev meeting, we are using some language features which aren't supported in electron<3.

Specifically there are instances of `Array.values()` in (at least) the debug plugin which should be removed.

According to [node.green](https://node.green/) all other ES2015 language features are supported by our current target runtimes.

It would also be extremely useful to include checks to avoid using unsupported language features in future (via tslint,  node, or @types/node versions perhaps?).

**Comment by thegecko** [comment]
@akosyakov Is this something you wanted to look into?

**Comment by akosyakov** [comment]
@thegecko I can have a look into fixing the debug extension.

Someone else can have a look into the rest, like adding checks or 3rd party polyfills if there is no way to check.

There are 2 more things come to my mind:
- if we introduce checks we should also generate them in the [Theia extension generator](https://github.com/theia-ide/generator-theia-extension) that external extensions don't use these features as well.
- @simark wanted to switch from es6 to es7 (esnext) libs, but now I am not sure whether it is a good idea since we have problems even with es6.

**Comment by thegecko** [comment]
I believe this is no longer an issue since our move to Electron 3/node 10
