### ISSUE TITLE
[Search in folder] Missing tooltip in the dialog view

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3742]
Search In Folder dialog view missing some tooltip
- Icon beside the Replace text box: "Replace all (CTRL + ALT+ENTER)
- 3 dots icon: Toggle Search Details
- IN textbox " files to exclude", missing the icon + tooltip: Use Exclude Settings and Ignore Files

**Comment by vince-fugnitto** [comment]
@lmcbout 
The third bullet point does not apply since we already have the option to ignore files with the `eye` icon (see below) and it already has the tooltip available.

<img width="764" alt="screen shot 2018-12-05 at 10 11 37 am" src="https://user-images.githubusercontent.com/40359487/49522786-6f2f4b80-f876-11e8-8699-4a79427543af.png">

**Comment by vince-fugnitto** [comment]
@lmcbout it probably shouldn't be in this issue since it's not related to tooltips, you can open a new issue to discuss with others

**Comment by lmcbout** [comment]
@vince-fugnitto  I am OK with this implementation, it is just that you mention to me earlier that you were looking to similar experience with vscode, for me it doesn't have to be 100% exactly the same

**Comment by vince-fugnitto** [comment]
@lmcbout I agree it does not have to be the same, but if you are referring to https://github.com/theia-ide/theia/pull/3626#issuecomment-444499484, the reason we have `files to include` and not `folders to include` is because we offer a regexp to the search term. 

When we search for `*.json` we are looking for all json files. 
If we provide `packages/core/src/browser/**` we are not saying look for that **folder** but rather the files narrowed down by the search term.
