### ISSUE TITLE
[Electron] the first-spawned window will kill the backend server

### ISSUE THREAD

**Issue by sr229** [theia-ide/theia#3788]
Reproduction is as follows:
- Spawn a Electron Theia process
- Open a workspace that opens another window.
- kill the first-spawned process

Expected: Each window has their own server process and won't affect the closure of the other.
Result: Backend process is one to many relationship, and closing the first electron process kills the backend, which makes the second electron process unusable.

**Comment by kittaakos** [comment]
I could not reproduce this issue on macOS with 126ac7495.

We used to have a bug that caused a backend crash when one selected a new workspace. See [here](https://github.com/theia-ide/theia/issues/4349) and [here](https://github.com/theia-ide/theia/issues/3242). I believe after getting rid of the cluster mode, this issue is gone.

Please reopen if required.
