### ISSUE TITLE
Help about missing some information

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#3886]
Help -> About:
- we should sort the list of extensions
- We should add an option "Copy" to clipboard like VSCODE
- Have the date of this build
Note: can we put the Extension name in  column and the associated version in another column, so we could sort by the version / name, we can also align the version 

- Any other useful info that could help to debug if the end-user use the  "Copy" button to read the info and put it in an issue

![image](https://user-images.githubusercontent.com/419051/50347711-92a7f680-0504-11e9-9810-6f5d30867a54.png)

**Comment by vince-fugnitto** [comment]
I'm not 100% convinced the current information in the `About` is entirely useful for end-users since they would have a product and not worry about which theia-extensions their product currently has installed. We can however always update the about to display whatever information we'd think would be most pertinent to end-users and in whichever format we'd desire.
