### ISSUE TITLE
[monaco/editor] onWillSave API leads to concurrency problems

### ISSUE THREAD

**Issue by marechal-p** [theia-ide/theia#3888]
VS Code doesn't parallelize edits, and instead they manage a list of listeners/callbacks that get triggered one after the other.

In our case, we first dispatch the event to everyone, then wait for them all. But at this point, every edits are computed at the same time, from the same base document model. This can lead to conflicts, where two contributions want to edit the same region.

I don't really know how to handle that, first thought would be to add an alternative API that would address this issue, and deprecate the other one (but keeping it for some time).

**Comment by marechal-p** [comment]
https://github.com/theia-ide/theia/pull/3867#discussion_r243056683

**Comment by akosyakov** [comment]
@marechal-p I don't think we should deprecate `onWillSave` since it should be exposed via the plugin API, similar as in https://code.visualstudio.com/api/references/vscode-api. Could you elaborate on alternative APIs? In VS Code APIs I see only `onDidSave` and `onWillSave`, our `onWillSave` mimick one form VS Code.

**Comment by marechal-p** [comment]
I think you are right in that the API could stay the way it is. In VS Code, what happens is that they trigger [listeners sequentially](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/api/node/extHostDocumentSaveParticipant.ts#L58-L69). Maybe by just changing the `EventEmitter` -that we internally use- for something else could do the trick.
