### ISSUE TITLE
[plugin] support octicon in the status-bar text

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#4005]
https://code.visualstudio.com/api/references/vscode-api#StatusBarItem

@svenefftinge Would it be fine to include next to fontawesome icons?

**Comment by vazexqi** [comment]
_Piggy backing onto this bug since it seems related, I can open a new one if you want_.

We are experimenting with using .vsix in Theia. We have noticed that icons (octicons) in labels are supported in VS Code per https://code.visualstudio.com/api/references/icons-in-labels

However, this currently doesn't work consistently in Theia. It works on the status bar in Theia but not in the quick pick. See the attached screenshot. 

<img width="630" alt="Screen Shot 2019-03-21 at 7 08 48 AM" src="https://user-images.githubusercontent.com/54414/54758561-a0bfee80-4ba9-11e9-99cf-bb3226be955d.png">

The `$(plus)` should be the [+](https://octicons.github.com/icon/plus/) symbol in octicons.

**Comment by akosyakov** [comment]
yes, we should support it

**Comment by akosyakov** [comment]
It's required fro scm as well to show status bar icons from git extension.

**Comment by akosyakov** [comment]
@vazexqi extracted #5412 for your issue
