### ISSUE TITLE
Shortcut Keys

### ISSUE THREAD

**Issue by aaronbartell** [theia-ide/theia#408]
It would be great to have shortcut keys for things like the following: 

- Opening a new terminal tab
- Next Tab, Previous Tab

**Comment by epatpol** [comment]
@hexa00 we should start thinking about default keybindings values for both browser/electron versions. Maybe we could have a spreadsheet with all commands we want to support and two columns for browser shortcut/electron shortcut. I can add a keybinding for opening a new terminal, but I'm not sure which keybinding it should be...

**Comment by aaronbartell** [comment]
>I can add a keybinding for opening a new terminal, but I'm not sure which keybinding it should be...

I'd vote to follow the lead of VSCode, both in defaults and the approach to override.

**Comment by hexa00** [comment]
@epatpol I think we should use same keybindings for browser and electron however ?

I guess there's some keybindings we don't want to override from the browser. Maybe listing that would be a nice start ?

**Comment by epatpol** [comment]
Yes @hexa00 that's what I was wondering too, i.e nextTab and previousTab as ctrl-tab/ctrl-shift-tab usually makes sense, but in our case that won't work in the browser (unless we find a way to override it...)

**Comment by hexa00** [comment]
One thing I like from emacs and that may be applicable here to get out of the browser/electron problem was the use of prefixes.

So you could have some types of commands start by a prefix and others use another one so that you would get kinda namespaces for keybindings.

Like next tab prev/tab could be like : Terminal prefix + key , like C-T + arrows ?
And using like next / previews windows could be like C-X + arrows or something like that...

This might not be separated properly however but you get the idea...

We need to think about this more, and I hope we can do better than just copy VSCode..

**Comment by akosyakov** [comment]
@epatpol Can be closed?
