### ISSUE TITLE
[search in workspace] Unstable ordering of search results 

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#4113]
The ordering of search results isn't ordered consistently but is different on every search.

Reproduce:

[![Open in Gitpod](https://gitpod.io/button/open-in-gitpod.svg)](https://gitpod.io#snapshot/c179d4e8-9eed-46b7-97d2-7b6fc0fa05b6)

(trigger search several times)

**Comment by vince-fugnitto** [comment]
@svenefftinge I wonder if it would be useful to not trigger re-search whenever the search and options remain the same. Keeping the history of past searches can be useful since `vscode` has the mechanism to list past searches when the keybiding <kbd>alt</kbd>+<kbd>⬆</kbd> or  <kbd>alt</kbd>+<kbd>⬇</kbd> on the search input field.

I also noticed `ripgrep` has the `--sort` flag but using it means searches will be performed sequentially over parallel.

**Comment by kittaakos** [comment]
Moved from https://github.com/theia-ide/theia/issues/4416#issue-413977996:

I got back different hit counts for the same query term. See attached screencast.
I set the inclusion pattern, after hitting `Esc` I got back different result numbers. It is clear, we limit the search to 2k result items by default, but as a user, I expect to have the same result for the same search.

![screencast 2019-02-25 08-55-31](https://user-images.githubusercontent.com/1405703/53322458-c1af5f80-38db-11e9-8d36-b3fcfc61f2e1.gif)
