### ISSUE TITLE
Redesign our test suite tooling

### ISSUE THREAD

**Issue by hexa00** [theia-ide/theia#415]
The idea would be to have test suite that can:

-   Run node unit tests
-   Run browsers unit tests in chrome and possibly others
-   Support LCOV output code coverage for node and browser tests

I'm looking at https://github.com/testem/testem with https://github.com/testem/testem/tree/master/examples/coverage_istanbul and possibly jasmine + https://github.com/jasmine/gulp-jasmine-browser

Note also that this is NOT for UI testing but more unit testing of frontend code
We need to investigate if we can check the DOM however with this, in which case we could consider it ui testing too.

**Comment by hexa00** [comment]
See also #107

**Comment by hexa00** [comment]
Notes from my research:

 - We can now use chrome headless rather then PhamtomJS so let's use that
 - We can continue to use istanbul for code coverage I think
 - I'm not sure we we need to switch from mocha to jasmine but jasmine chrome headless seems better

**Comment by akosyakov** [comment]
I have not looked at jasmine, but please have the following concern in mind: We had an experience with karma in another project. Karma tests require the presence of DOM. It turned out that it is really hard to run and debug such tests, e.g. I don't have an idea how to debug an individual DOM-based test from VS code.

So instead of testing UI components with the real DOM and using karma, PhamtomJS or headless chrome, we've decided to develop UI components in such way that its state and functionality can be tested with pure node tests without DOM. It leads to a better internal structure (because of separation state/rendering), fast turnarounds (no DOM) and the light test setup (pure node.js).

**Comment by hexa00** [comment]
But how do you test for example that the navigator does render the proper tree ?
Or that you can start a terminal ?
Or anything that uses websockets ? Like testing a service via websocket from node?

Maybe I'm just missing some info still

**Comment by akosyakov** [comment]
> But how do you test for example that the navigator does render the proper tree ?

It is usually straightforward to test manually, particularly in that case the VDOM can be tested.

It is harder to test, for example, the node expansion logic taking into account different kind of nodes and the current selection. I would prefer that such logic is separated from the rendering and tested with pure node tests.

> Or that you can start a terminal ?
Or anything that uses websockets ? Like testing a service via websocket from node?

I don't say that we should not have UI/integration tests and should not look at DOM testing technologies. We should have a reasonable amount of them.

I am mostly concerned by:
> Note also that this is NOT for UI testing but more unit testing of frontend code

I do think that unit testing should happen via pure node tests without DOM. And developers should spend more time designing and testing the UI component state/functionality without rendering it.

**Comment by hexa00** [comment]
I'm a bit confused let's say I would like to test the TerminalWidget or any widget, since that depends on phosphor I can't run that purely in node right ?

So should it be that the business logic of widgets gets into another class and this should be tested by node ?

So that we should move most of what is in the TerminalWidget to like TerminalWidgetController ? (I'm not sure what to name that?)

I thought even without looking at the DOM that we should test for example the TerminalWidget in a using chrome headless driven by a test framework like mocha or something so that we can do unit tests for the frontend code... For sure we can't have 0 logic in the Widgets etc..

**Comment by akosyakov** [comment]
> I'm a bit confused let's say I would like to test the TerminalWidget or any widget, since that depends on phosphor I can't run that purely in node right ?

right

> So should it be that the business logic of widgets gets into another class and this should be tested by node ?
So that we should move most of what is in the TerminalWidget to like TerminalWidgetController ? (I'm not sure what to name that?)

I follow usually `Widget` + `WidgetModel`, look at `TreeWidget` + `TreeModel`.
I don't like `Controller`, since it comes from `MVC` and it is something we are trying to avoid and use a unidirectional data flow instead, i.e.:
- `Model` provides the read-only access to the state, state change events, and functions to mutate the state, e.g. the tree data, the current selection, the expansion state, the navigation logic;
- `Widget` renders on the state changes and call mutation functions on callbacks

> I thought even without looking at the DOM that we should test for example the TerminalWidget using chrome headless driven by a test framework like mocha or something so that we can do unit tests for the frontend code... For sure we can't have 0 logic in the Widgets etc..

- `Model` can be explicitly tested with pure node tests
- `Widget` has only rendering logic which one should see to test
-  one can as well test `Model` via `Widget`, but it is expensive and can lead to leaking the model logic to widgets

**Comment by hexa00** [comment]
OK thanks I'll check this out. And possibly rework the terminal widget too.

**Comment by hexa00** [comment]
@akosyakov Thinking about this more, can you create a websocket client in node ? 
To test a server in the backend?

**Comment by akosyakov** [comment]
> Thinking about this more, can you create a websocket client in node ?

I think you can with `ws` package.

> To test a server in the backend?

We also can skip websockets part, e.g. if there are`MyClient` and `MyServer` we can mock one of them to test another or connect them directly to test directly.

**Comment by hexa00** [comment]
@akosyakov to debug tests with karma seems like you can just attach to the chrome instance see: https://stackoverflow.com/questions/42805028/how-to-debug-karma-tests-in-visual-studio-code

Was that the only concern with karma?

**Comment by hexa00** [comment]
I think I understand what you mean in the sense that Karma can't do node tests ?

I think I'm going to go with testem, it can do node and browser, + coverage, the UI seems nice... 

Anyone have opinions on that ?

**Comment by akosyakov** [comment]
I know that one can attach from VS code, but steps look like that:
- comment out all tests which are you not interested to debug
- run karma tests from CLI
- attach from VS code
- refresh the browser to rerun tests

You get an idea how slow it is.

**Comment by kittaakos** [comment]
If you execute karma test from mocha, cannot you specify ` -- --grep=foo` to run only the `foo` test? So you do not have to comment out all the test. At least, that works with mocha.

On the other hand, loading Monaco into the browser tests will be a pain for sure.

**Comment by akosyakov** [comment]
I want to select the file, put the breakpoint, run VS Code task and debug and don't want to hustle around with CLI arguments, browsers and page refreshing.

**Comment by hexa00** [comment]
OK yes sounds reasonable, I'll keep that in mind

**Comment by hexa00** [comment]
Given the previous comments and that I tested successfully a service from node.
I'll close this and we can test pretty much everything through node and the rest through UI testing with selenium.
