### ISSUE TITLE
[cpp] setting active build configuration does not trigger clangd until reload

### ISSUE THREAD

**Issue by vince-fugnitto** [theia-ide/theia#4282]
A reload is necessary when attempting to set **active cpp build configuration** as initialisation is not immediately triggered. This may be potentially the reason the cpp UI tests no longer work correctly.

**Comment by simark** [comment]
@akosyakov, since commit bfb235a0d7b7c9efd5f3995205b5c864f4afa536, calling restart on the language client does not cause Theia to instantiate a new language client, we keep re-using the same object.  Therefore, the language client's createOptions method is not called again.  The cpp package was counting on this getting called again to send new parameters to clangd when changing the active build configuration.

Do you have a suggestion on how to fix this?

**Comment by akosyakov** [comment]
Unfortunately the language client is not designed to have more than one instance. It starts leaking them.

`initializationOptions` can be a function instead of a value, which is called whenever initialization happens.

**Comment by simark** [comment]
> `initializationOptions` can be a function instead of a value, which is called whenever initialization happens.

Ok, this sounds like a proper solution, but would require changes at multiple levels.  For now, I'll fix it locally in cpp by overriding `initializationOptions` in the existing client when we want to change it.
