### ISSUE TITLE
View Container widget improvements

### ISSUE THREAD

**Issue by olexii4** [theia-ide/theia#4386]
We should improve the TreeView widget:
- [ ] Restore the previous widget state after reloading.
- [ ] Add each view container into the 'View' menu.
- [x] Remove all unnecessary timers from the widget implementation. Add code clean up.

**Comment by akosyakov** [comment]
Please see https://github.com/theia-ide/theia/pull/5665

It aims to bring state restoration of view containers and views.

> Add each view container into the 'View' menu.

It will also provide a command to open a view otherwise there is no a way to open a view container after closing it. Not sure about adding `View` menu, it will pollute it fast. We can add view containers though instead.

**Comment by akosyakov** [comment]
@olexii4 @evidolob Could you have a look at https://github.com/theia-ide/theia/pull/5665? It:
- allows to toggle view containers contributed by the plugin system, so a user can reopens them
- should preserve plugin tree view layout state between user sessions

The PR is not final, there will be more changes to remove unnecessary changes, but feedback from the user perspective is welcomed.

**Comment by akosyakov** [comment]
In #5665 there is also `Open View` command now to activate any contributed view. And `view` quick palette prefix.

**Comment by akosyakov** [comment]
I believe everything was addressed in #5665
