### ISSUE TITLE
Werid Scroll To Bottom behavior

### ISSUE THREAD

**Issue by duemaster** [theia-ide/theia#4390]
I am using [react-scroll-to-bottom](https://www.npmjs.com/package/react-scroll-to-bottom) to enable auto scrolling of list items in a widget. The widget receives updates through events, which adds items to a list and auto scrolls down.

However, I am noticing some werid scrolling behavior.

This is how I replicate it:
1. Widget is in a collapsed state (Label shown, but widget is not open)
2. Updates come in and widget adds new item to the list.
3. User clicks open widget, scroll to bottom animation starts.

This feels werid as I would expect the widget to auto scroll down even if it was in the collapsed state.

Is this because when in a collapsed state, the DOM element cannot be found so scrolling cannot work?

**Comment by vince-fugnitto** [comment]
I'm not sure if this is the best place to ask the question, perhaps it'd be more appropriate to ask 
on our general chat forum https://spectrum.chat/. 

I'm no react expert but if you have the code hosted somewhere (github or otherwise) or are able to start a `gitpod` instance and share it, I can take a closer look at it for you, but based on your description nothing immediately comes to mind as to why it may not work :(

**Comment by duemaster** [comment]
@vince-fugnitto 
I have replicated the issue [here](https://github.com/duemaster/theia-widget-scrolling-issue).
I tried making it work on gitpod but couldn't get the terminal to start.

**Comment by vince-fugnitto** [comment]
@duemaster I also noticed that if you have theia opened in a tab, browse a different tab for a while and return to theia, the same behaviour you described above is observed which leads me to believe `react` optimises it's updates by only updating if you are currently in the **viewport**. I'll investigate further :)

**Comment by duemaster** [comment]
@vince-fugnitto 
Hmm, that's interesting. I checked the [react-scroll-to-bottom](https://www.npmjs.com/package/react-scroll-to-bottom) library description and it states:

React container that will auto scroll to bottom or top if new content is added and **viewport** is at the bottom, similar to tail -f. Otherwise, a "jump to bottom" button will be shown to allow user to quickly jump to bottom.

Could it be that it is actually the library and not react that is checking if it is visible?

**Comment by vince-fugnitto** [comment]
@duemaster that is certainly a possible hypothesis, perhaps it may be worthwhile to open an issue on the `react-scroll-to-bottom` GitHub page and ask for clarifications / help :) I believe it has to do with the viewport, since in both cases (widget hidden and a different tab) scrolling only reoccurs when the widget is back in the viewport.

**Comment by duemaster** [comment]
@vince-fugnitto 
I will do that. Thanks for the help!

**Comment by vince-fugnitto** [comment]
@duemaster No problem! I'll close the issue for the moment but please feel free to re-open it if the issue persists or you have more questions :)
