### ISSUE TITLE
[text-mate] Memory issues

### ISSUE THREAD

**Issue by kittaakos** [theia-ide/theia#4434]
We seem to have an issue with the `MonacoTextMateService`. I am not sure about the real cause yet.

Steps to reproduce:
 - Clone from the `master`.
 - Open the `README.MD` in the editor.
 - Refresh the browser a few times and create a heap dump.

In the end, you will get
```
onigasm.js:4 Uncaught (in promise) RangeError: WebAssembly.Memory(): could not allocate memory
    at Onigasm (onigasm.js:4)
    at Promise (onigasmH.js:6)
    at new Promise (<anonymous>)
    at initModule (onigasmH.js:5)
    at Object.loadWASM (onigasmH.js:38)
    at Object.<anonymous> (monaco-textmate-frontend-bindings.ts:61)
    at step (monaco-textmate-frontend-bindings.ts:15)
    at Object.next (monaco-textmate-frontend-bindings.ts:15)
    at monaco-textmate-frontend-bindings.ts:15
    at new Promise (<anonymous>)
```

**Comment by akosyakov** [comment]
@kittaakos is it the same on stable connection? @svenefftinge it sounds quite bad

**Comment by marcdumais-work** [comment]
At first for a little while it seemed I was able to reproduce this. Resident and virtual memory (as reported by `htop`) for a few chrome processes, were increasing significantly with each reload, until the browser I think ran our of memory:

```
index.js:82 Error: Loading chunk 43 failed.
(error: http://localhost:3005/43.bundle.js)
    at HTMLScriptElement.onScriptComplete (bootstrap:114)
./src-gen/frontend/index.js.module.exports.Promise.resolve.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.then.catch.reason @ index.js:82
Promise.catch (async)
./src-gen/frontend/index.js @ index.js:79
__webpack_require__ @ bootstrap:63
(anonymous) @ bootstrap:196
(anonymous) @ bootstrap:196
```

While I was able to reproduce, it seemed that closing all editors but keeping the workspace set, the problem was still happening and getting worse each subsequent reload. This makes me think that the leak may not be necessarily related to Textmate, but it could have been by chance that this happened to be the first component to request memory after is was exhausted.

Then I closed the workspace and I restarted the BE, and things seem to go back to normal; I tried a few more times and  I am not able to reproduce any more.

**Comment by kittaakos** [comment]
> This makes me think that the leak may not be necessarily related to Textmate

I am positive. Comment out https://github.com/theia-ide/theia/blob/b1ef055e2edcaaf29d22797a3d416ba710ce9f9d/packages/monaco/src/browser/textmate/monaco-textmate-frontend-bindings.ts#L61

and the memory leak is gone. Of course, the syntax highlighting will be off too.

**Comment by AlexTugarev** [comment]
@kittaakos, it looks like this happens only in Chrome, it's fine FF. And it also looks like it's a general WebAssembly issue, as it's same for other WebAssembly [examples](https://forum.golangbridge.org/t/chrome-for-ms-windows-cannot-load-wasm-code-after-refresh-4-times/10421/16).

**Comment by AlexTugarev** [comment]
@kittaakos, please retest this having the DevTools *not* opened.

It's a [DevTools bug](https://bugs.chromium.org/p/chromium/issues/detail?id=912153).

**Comment by kittaakos** [comment]
I have verified it. it is a Chrome issue.
