### ISSUE TITLE
[plugin] support multiple remote connection of plugins

### ISSUE THREAD

**Issue by ensorrow** [theia-ide/theia#4509]
### Is there any plan to fix this problem recently?

![image](https://user-images.githubusercontent.com/13199771/54019904-60369d00-41c7-11e9-9ff2-047063a8c63e.png)

Plugins will be quite useless without this feature...

**Comment by akosyakov** [comment]
@ensorrow Could you have a look?

**Comment by akosyakov** [comment]
So does it mean that plugins only work for last page? @benoitf

**Comment by ensorrow** [comment]
> So does it mean that plugins only work for last page? @benoitf

Yes, that's the problem. Only the last client can receive the message from server.

**Comment by akosyakov** [comment]
Yes, just verified that it is broken.

**Comment by akosyakov** [comment]
Right now the backend always run one plugin host process. It won't work for multiple clients since each client should have own context (opened dirty editors and so on). It's quite mind boggling to refactor to give each client its own plugin host process (especially on Friday evening), will see what can be done next week :)

**Comment by benoitf** [comment]
> akosyakov : So does it mean that plugins only work for last page? @benoitf
yes, I think there is an open issue but I'm not finding it :-/

**Comment by ensorrow** [comment]
Hope you can close the issue this week😉.That’s the only problem we are facing now on developing a Theia based IDE.Theia is awesome.

**Comment by ensorrow** [comment]
Awesome!!!

**Comment by svenefftinge** [comment]
Reopening as it is not merged, yet.
