### ISSUE TITLE
[workspace] workspace.findFiles does not work correct

### ISSUE THREAD

**Issue by svor** [theia-ide/theia#4599]
### Description
As a result of `workspace.findFiles('**​/*.js', '**​/node_modules/**', 10)` I expect to get only `.js` files from the workspace. But files like `file1.jsblabla`, `file2.js.bla` also match to this pattern.

**Comment by akosyakov** [comment]
yeah, I've noticed it as well, we append/prepend include glob patterns with `*` for some reasons. Have not touched it, @elaihau do you have an idea it is implemented like that?

**Comment by akosyakov** [comment]
@svor vscode APIs right? in Theia extension APIs the first argument is not include glob pattern.

**Comment by elaihau** [comment]
a glob of `**​/*.js` is treated as `**​/*.js*` in the service. 
I implemented like that because it **was** directly used by the file-quick-open (I don't want users to get different results by searching with `**/package` and `package`).
Since Anton made glob search an option and not used by file-quick-open, I don't think `**​/*.js` should be converted to `**​/*.js*` any more.

**Comment by svor** [comment]
@akosyakov You are right! Here it is https://github.com/theia-ide/theia/blob/master/packages/plugin/src/theia.d.ts#L4085
