### ISSUE TITLE
[UX] Creating multiple folders with / in the name

### ISSUE THREAD

**Issue by benoitf** [theia-ide/theia#4741]
### Description
Let say I need to create `src/main/java` folder, I need to create first `src` then `main` then `java` while typically on IDE I can enter directly `src/main/java` and all three folders are automatically created

In Theia it displays `Invalid name, try other`

### Reproduction Steps
Menu File / New Folder
enter `src/main/java`

**OS and Theia version:**
macOS / master

**Diagnostics:** 
N/A

**Comment by vince-fugnitto** [comment]
@benoitf I'm wondering, would it be useful in your case to also be able to flatten the Explorer. I know that Java projects often have very long package names such as (`com.domain.package.task`).

 Instead of displaying the following in the Explorer:

```
+ com
  + domain
    + package
      + task 
        Task.java
...
```

We can optimize the display to:
```
+ com/domain/package/task
  Task.java
...
```

In essence, if we find that there are a single child node in a directory which itself is a directory then we can offer a flattened Explorer or at least be able to toggle to flatten. My only worry is finding the proper mechanism to add an entry in the middle, say `package`. What are your thoughts?
 There is an issue present in VSCode for such a functionality https://github.com/Microsoft/vscode/issues/41627

**Comment by benoitf** [comment]
@vince-fugnitto yes that's also a nice improvement like it's done on github explorer as well
to flatten view when there is only one folder in child.

I like that ❤️

**Comment by benoitf** [comment]
@vince-fugnitto about your issue on entry in the middle, new Folder or new Package could contain a pre-populate content

**Comment by vince-fugnitto** [comment]
> @vince-fugnitto yes that's also a nice improvement like it's done on github explorer as well
> to flatten view when there is only one folder in child.
> 
> I like that

I added a separate issue highlighting the proposal https://github.com/theia-ide/theia/issues/4783 :smiley:
