### ISSUE TITLE
[electron example] Add plugin support

### ISSUE THREAD

**Issue by ciampolo** [theia-ide/theia#4802]
### Description
So I have placed the vscode chrome debug extension inside the theia git root folder/plugins. When I run the theia electron variant there isn't any plugin view at all and the extension isn't registered (electron theia says there is no "Chrome" debug type). I checked the stdout of the yarn run start command and the logs of the devtools, nothing about plugins or the chrome debugger. This also happens without any plugins at all. When I use the Browser variant everything works flawlessly. 

OS: Linux
Theia: Latest upstream and 0.5.0

Am I missing something obvious or is this just a bug?

**Comment by marcdumais-work** [comment]
The plugin extensions are not currently part of the [Electron example application](https://github.com/theia-ide/theia/blob/master/examples/electron/package.json#L46). I do not know if it was just missed or if it's because there's an issue.

Untested patch where they are added [here](https://github.com/marcdumais-work/theia/commit/a399231e1924679b7b68f90edfc3e91a7d548380)

**Comment by ciampolo** [comment]
While the plugin extension is loaded correctly now it doesn't actually load the vscode extensions.

> root ERROR Cannot find a service for the path: /services/plugin-ext
> root ERROR Cannot find a service for the path: /services/plugin-paths

Your reverts https://github.com/theia-ide/theia/pull/3737 so it should work but apparently there is other code left to modify.

**Comment by benoitf** [comment]
FYI it was disable by https://github.com/theia-ide/theia/issues/3723

**Comment by akosyakov** [comment]
Someone should fix #3651 and #2210 then we can enable it.
