### ISSUE TITLE
[keybinding] Support international/US layout

### ISSUE THREAD

**Issue by AlexTugarev** [theia-ide/theia#4986]
see https://github.com/theia-ide/theia/pull/4998#discussion_r278448654

**Comment by akosyakov** [comment]
cc @spoenemann

**Comment by spoenemann** [comment]
It works for me. Which keyboard layout, browser, language setting do you use?

Note that the keybinding for _Open New Terminal_ is defined as _ctrl+shift+`_. In VS Code that's the keybinding for _Toggle Integrated Terminal_. We have defined _ctrl+`_  as _Open New Terminal (In Active Workspace)_, but on German keyboards that's in conflict with the other keybinding because we don't have a ` key, but only a ´ key, and need to press shift+´ in order to write `.

**Comment by AlexTugarev** [comment]
@spoenemann, I'm using latest Chrome and US keeb layout. 

Checking with latest master locally again...

**Comment by AlexTugarev** [comment]
![2019-04-25 09 04 50](https://user-images.githubusercontent.com/914497/56715912-429ea200-6739-11e9-8b4a-5b0887da7dde.gif)

broken it is.
