### ISSUE TITLE
[vscode] support editor/title context menus for web views

### ISSUE THREAD

**Issue by 502647092** [theia-ide/theia#5515]
### Description
preview toolbar also not support
VSCode
![image](https://user-images.githubusercontent.com/10203793/59731262-f9218d80-9277-11e9-8992-b9abdd8b72d4.png)
Theia
![image](https://user-images.githubusercontent.com/10203793/59731274-06d71300-9278-11e9-899f-16bd522aac79.png)

### Reproduction Steps
Download vscode plugin REST Client(humao.rest-client)
create a new http file
Send Request
look response

**OS and Theia version:**
**Diagnostics:**

**Comment by 502647092** [comment]
preview toolbar also not support
VSCode
![image](https://user-images.githubusercontent.com/10203793/59731262-f9218d80-9277-11e9-8992-b9abdd8b72d4.png)
Theia
![image](https://user-images.githubusercontent.com/10203793/59731274-06d71300-9278-11e9-899f-16bd522aac79.png)

**Comment by akosyakov** [comment]
These actions are contributed via `editor/title` contribution point for the webview: https://github.com/Huachao/vscode-restclient/blob/ea54abe5e5e54eccd002dbef7ff1693d48983f9d/package.json#L205-L236

The difference between Theia and VS Code is that everything visible in the main area is an editor for VS Code from the perspective of commands and contribution points. In Theia an editor is an textual editor. Right now it's only possible to contribute menu items to textual editor because of it. We should rather base the check on whether a widget is a navigatable or not, i.e. it backed up by a file resource.
