### ISSUE TITLE
[editor] deleting a file should be reflected in the corresponding editor

### ISSUE THREAD

**Issue by marcdumais-work** [theia-ide/theia#560]
If a file is opened in an editor, deleting it ATM leaves the corresponding editor opened. It should probably be closed.

See also #230 . 

This has the side-effect of breaking the layout restoration, if the Theia client is closed with that non-existing file opened in an editor : 

``` javascript
localhost/:1 Uncaught (in promise) A resource provider for 'file:///tmp/a/theia/examples/browser/aaa.txt' is not registered.
Promise rejected (async)
(anonymous) @ shell-layout-restorer.ts:78
ShellLayoutRestorer.inflate @ shell-layout-restorer.ts:73
(anonymous) @ shell-layout-restorer.ts:28
Promise resolved (async)
ShellLayoutRestorer.onStart @ shell-layout-restorer.ts:25
FrontendApplication.startContributions @ frontend-application.ts:110
FrontendApplication.start @ frontend-application.ts:67
start @ index.js:29
Promise resolved (async)
Object.defineProperty.value @ index.js:48
__webpack_require__ @ bootstrap a28e50b24baf5c30315c:688
Object.defineProperty.value @ bootstrap a28e50b24baf5c30315c:789
(anonymous) @ bootstrap a28e50b24baf5c30315c:789
```

**Comment by hexa00** [comment]
I don't think it should be closed!

It saved me a few times to be able to save a buffer I still had in memory while I deleted the file accidentally.

We could recover gracefully instead when recovering a session if the file is not there... and just not show that file.

**Comment by marcdumais-work** [comment]
I guess this can happen, but you have to be lucky enough to have the file, that you accidentally deleted, opened at that time. Maybe a more general mechanism, for example where a deleted file is moved in a "thrash" folder, might be better?

**Comment by hexa00** [comment]
I would just rename the title of the tab like (deleted from disk) like vscode does.
emacs does something similar also

**Comment by marcdumais-work** [comment]
Renamed this issue to keep our options open - we could close the editor or have a way to show the user that the underlying file is deleted

**Comment by lmcbout** [comment]
Should we close the file or not from the editor when we delete the file from the back-end?
AS @hexa00  mentioned, it could be good to keep it open in editor. I agree with him since there is no confirmation like "Are you sure you want to delete" when deleting a file. It could be  by accident  removing a file.  Also I agree with @marcdumais-work  when he mentioned that there should be an indicatiion in the editor that the file opened does not exist anymore on the back-end.  It could also be that the file in the editor is in dirty state, so it a possibilioty the user deleted the file by mistake, so he would still have an option to recover easily from it.  On the other hand, when a user delete a file from the filesystem, he would like to remove all traces from that file. In this case should we delete the file from his filesystem and  move it to trash, so he still have a way to recover it if deleted by mistake ?
