### ISSUE TITLE
[problems] show total number of problems on the widget tab

### ISSUE THREAD

**Issue by fangnx** [theia-ide/theia#5602]
There should be a small icon showing the total number of problems present. It can be displayed on the tab of the `problems` widget.

In VS Code:
![image](https://user-images.githubusercontent.com/25921074/60298860-6d53d500-98f9-11e9-86eb-eaecc2d797b5.png)

**Comment by vince-fugnitto** [comment]
I don't think it should be solely done for the `problems-widget` it should be more generic to all widgets like https://github.com/theia-ide/theia/issues/4782 (since widgets can be docked anywhere) Also, the `problems-widget` is actually one of the few widgets which would not really benefit from this enhancement since the number or errors and warnings are already displayed in the statusbar.

**Comment by fangnx** [comment]
> I don't think it should be solely done for the `problems-widget` it should be more generic to all widgets like #4782 (since widgets can be docked anywhere) Also, the `problems-widget` is actually one of the few widgets which would not really benefit from this enhancement since the number or errors and warnings are already displayed in the statusbar.

I agree it should be done in a more generic way.

**Comment by vince-fugnitto** [comment]
@fangnx can we close the issue in favor of #4782 ?
