### ISSUE TITLE
Add debug configuration for the first time is hard coded to use .theia folder

### ISSUE THREAD

**Issue by amiramw** [theia-ide/theia#5634]
### Description
when you add debug configuration for the first time it also ignores the preference (.vscode and .theia folders): https://github.com/theia-ide/theia/blob/af00d42b3d71b0d0b723cb970fefafb9c8500281/packages/debug/src/browser/debug-configuration-manager.ts#L255

### Reproduction Steps
1. Clean .vscode or .theia folder from the workspace if there is any
1. Override preference configuration to getPaths return only .vscode
1. Run command add debug configuration
1. The configuration is created anyway in .theia folder due to the hard coded name in the code above

**OS and Theia version:** All

**Diagnostics:** 
N/A

### Question:
If I want to fix it what is the correct API to call? Is it PreferenceConfigurations.getPaths()[0] or is there any abstraction on top of it that I should use?

**Comment by akosyakov** [comment]
One does not need to override anything to reproduce the issue, it should also work in the following case:
- make sure that `.theia` folder does not contain any settings
- create `.vscode` folder and settings file in it
- try to add a new launch configuration
- since there is only vscode settings, launch file should be created in `.vscode` folder

We have such logic already when we use `PreferenceService` to set preferences. Maybe we can reuse it somehow.

**Comment by akosyakov** [comment]
@amiramw maybe just for your use case we can replace hardcoded variable with the first path? then it should work for you? Could you make a PR?
