### ISSUE TITLE
"configure task" should not add duplications to task.json

### ISSUE THREAD

**Issue by elaihau** [theia-ide/theia#5719]
### Description

Configuring the same task multiple time adds duplications to the tasks.json file

![Peek 2019-07-16 00-23](https://user-images.githubusercontent.com/37082801/61265882-5bc75580-a760-11e9-91f2-04367d3b4230.gif)

In VS code, if a detected task has been customized, the user won't be able to add a second customized config to tasks.json. 

### Reproduction Steps

1. take `npm install` for example, open "Run tasks"
2. configure `npm install`
3, repeat step 1 and 2
4, check data in tasks.json 

what happened: there are more than one objects added to `tasks.json` for `npm install`
what should happen: duplicated customization for the same detected task should be avoided

**Comment by RomanNikitenko** [comment]
It's strange...
I checked this case when I added 'Configure' action.
It looks like a regression...

**Comment by RomanNikitenko** [comment]
I'm tried to understand what could bring the regression and found that maybe [this PR](https://github.com/theia-ide/theia/pull/5024) changed the behavior.
WDYT?

So to check it, I did `git reset --hard 7fe439a30d53846a82d6b0c916de5a69b9da2c77` (commit **before** the changes from PR)
 It works well - after configuring the task is displayed as `configured` and it's impossible to add the same task twice.
Please see video: https://youtu.be/IQIeQugBeH0

Then I update my branch to commit **with changes** from the PR, so  `git reset --hard abd631fb173387dd558e2c616961490369c6987a`
After configuring the task is displayed as `detected` and it's possible to add the same task twice.
Please see video: https://youtu.be/E8nBofxhEQc

So if source of the issue is identified correctly, maybe it can help to speed up fixing of the bug...

**Comment by elaihau** [comment]
Thank you for the diagnosis @RomanNikitenko , it is really helpful !

I will see what my commit breaks and fix it asap.
