### ISSUE TITLE
[tasks]How to config tasks to show detected task

### ISSUE THREAD

**Issue by kpge** [theia-ide/theia#5737]
### Description
@elaihau  
I can not find detected tasks as the demo in #5024:
![image](https://user-images.githubusercontent.com/35068357/61371421-41f45280-a8c7-11e9-82f0-b3d22d72ca9b.png)
 What can I do to show the detected tasks?

### Reproduction Steps

**OS and Theia version:**
theia: 6021d795d61eafb214b234288f1568cae0cfa9f5
ubuntu: 18.04
chrome:  75.0.3770.100
**Diagnostics:**

**Comment by elaihau** [comment]
Sorry for the delaaaaaay, I haven't spent much time working recently.

To have detected tasks such as `npm xxx` displayed in the task quick-open, you will need to install VS Code extensions as Theia plugins. Take `npm install` for example, since it is detected by the `npm` extension, installing `npm` extension is needed. 

Unfortunately at the this moment we don't have a tool or a script that automates this process. You will need to go through the conversations and links in
1) https://spectrum.chat/theia/general/how-to-install-vscode-plugins-in-theia~04b0c6fa-ab64-4838-afb1-bb26923aae56
and 
2) https://spectrum.chat/theia/general/how-to-build-vscode-builtin-extensions-with-node-10~20783ad2-4a64-4b83-bd7c-06bf1ead155c
to figure out what the steps are.

**Comment by kpge** [comment]
> Sorry for the delaaaaaay, I haven't spent much time working recently.
> 
> To have detected tasks such as `npm xxx` displayed in the task quick-open, you will need to install VS Code extensions as Theia plugins. Take `npm install` for example, since it is detected by the `npm` extension, installing `npm` extension in Theia is needed.
> 
> Unfortunately at the this moment we don't have a tool or a script that automates this process. You will need to go through the conversations and links in
> 
> 1. https://spectrum.chat/theia/general/how-to-install-vscode-plugins-in-theia~04b0c6fa-ab64-4838-afb1-bb26923aae56
>    and
> 2. https://spectrum.chat/theia/general/how-to-build-vscode-builtin-extensions-with-node-10~20783ad2-4a64-4b83-bd7c-06bf1ead155c
>    to figure out what the steps are.

Thanks for your reply

**Comment by kpge** [comment]
@elaihau hi, elaihau, I've installed npm extension in theia , but I still can not find detected tasks, is my installed plugin right?
![image](https://user-images.githubusercontent.com/35068357/62341035-4ef28200-b514-11e9-92e3-ab674af1bd3a.png)

**Comment by kpge** [comment]
@elaihau I've found it , [npm](https://github.com/microsoft/vscode/tree/master/extensions/npm), thanks
