### ISSUE TITLE
keyboard shortcut for the task

### ISSUE THREAD

**Issue by akosyakov** [theia-ide/theia#5870]
See https://code.visualstudio.com/docs/editor/tasks#_binding-keyboard-shortcuts-to-tasks

cc @elaihau @RomanNikitenko

**Comment by Wicked7000** [comment]
I've got a start created for this but had a few questions regarding how we wanted this to work,
currently I'm using the VS code docs as a basis and have made the tasks in pretty much the exact same format as shown on the docs.

`
 {
        "keybinding": "ctrl+alt+/",
        "command": "workbench.action.tasks.runTask",
        "args": "[Task] list current dir"
    },
    {
        "keybinding": "ctrl+alt+s",
        "command": "workbench.action.tasks.runTask",
        "args": "[Task] Echo a string"
    }
`
For example this would run the those tasks with the set keybindings.

**Questions I have:**
- Is the format above acceptable or are there any modifications needed to be made to it? (such as the command being workbench.action.tasks.runTask)
- Currently the way I run tests is based on the label of that task, due to the fact there is no way to specify source, should I assume that their won't be duplicate tasks with the same label across sources? (If there are should the source also be specified in the keybinding configuration)
- Should there be an alert be raised if the task label specified can't be found? (Like the exit code notifications you get when you actually run a task).

If you'd like to have a look what I have currently (does not require a review as its currently in draft stage) you can look here: #5913

**Comment by akosyakov** [comment]
> Is the format above acceptable or are there any modifications needed to be made to it? (such as the command being workbench.action.tasks.runTask)

I suppose it should be generic functionality and work any command.

For rest questions, please use VS Code behaviour as a reference behaviour and align with it. It would be also good to share your findings with rest of committers via a comment.

Maybe @theia-ide/task-extension have answer already.
