### ISSUE TITLE
Drag & Drop a file to root is not available

### ISSUE THREAD

**Issue by lmcbout** [theia-ide/theia#5947]
### Description
Drag & Drop a file to the root folder is not possible with Theia version 0.9.0
We can Drag a file to any sub folder, but when Dragging to the root folder, there is no "DROP" section available.

### Reproduction Steps
![CopyToRootV090](https://user-images.githubusercontent.com/419051/63030138-d5498500-be7f-11e9-9af6-a4577749f787.gif)

**OS and Theia version:**
Theia 0.9.0
OS: Ubuntu 16.04

**Diagnostics:**

**Comment by vince-fugnitto** [comment]
@lmcbout would you like to take care of fixing it?

**Comment by akosyakov** [comment]
@lmcbout please rename issues, 0.9.0 does not have such changes, master state is 0.10.0

**Comment by kpge** [comment]
After we remove the root folder from explorer, there's no root folder node in single root workspace (multiple root workspace still have the root folder), so we can't drag a file to the root node.
In `theia@0.8.0`, drap a file in blank space is failed too, it's because that the blank space is not a folder node, but in Vscode  it points to the root folder node, so drap a file in blank space can move a file to root folder(the blank in multiple root workspace is pointed to the last root folder) .
V0.8.0:
![drap file](https://user-images.githubusercontent.com/35068357/63068369-85cd8c80-bf45-11e9-9c6d-3a93db5dc89e.gif)
Vscode:
![drap file in vscode](https://user-images.githubusercontent.com/35068357/63068472-cf1ddc00-bf45-11e9-9361-70b4094f319d.gif)
mulitiple root workspace in vscode:
![drap file in vscode2](https://user-images.githubusercontent.com/35068357/63081038-2c7d5180-bf75-11e9-8378-967b295b096d.gif)

**Comment by akosyakov** [comment]
Can we install listeners on widget node instead?

What are expectations in the multi-root scenario, nothing should be happened or we should add a folder as a workspace root?

**Comment by akosyakov** [comment]
@kpge feel free if you want to have a look into it

**Comment by kpge** [comment]
> What are expectations in the multi-root scenario, nothing should be happened or we should add a folder as a workspace root?

I think nothing should be happened  in the multi-root scenario, because the root folder had been shown in the explorer

And I will have a look at it in the weekend :)
