### ISSUE TITLE
Remove references to VSCode from development flow

### ISSUE THREAD

**Issue by gorkem** [theia-ide/theia#6079]
We should not reference VSCode for developing Theia. Instead our development flow should reference the either of the example builds. Right now it looks like debugging Theia is only done with VSCode.

**Comment by akosyakov** [comment]
Do you mean only in docs? We cannot remove vscode settings files, since there are no Theia based desktop distributions yet for dogfooding. If there would be I am for completely switching to Theia settings and force contributors to use electron version instead on desktop. Hope we get there later this year.

For now, I can rephrase that one can develop with any Theia IDE or VS Code.

**Comment by gorkem** [comment]
I meant on docs, especially the [development flow document](https://github.com/theia-ide/theia/blob/master/doc/Developing.md). It is OK for now if we have the settings files for both IDEs on the repos.
