### ISSUE TITLE
Refactor preferences to be mostly in the frontend

### ISSUE THREAD

**Issue by epatpol** [theia-ide/theia#772]
- Parsing/modifying preferences in the frontend
- Querying the user storage service to get the user preferences in the frontend (like #456)
- Have workspace-preferences rely on file changes (to be discussed further?)

This should also allow preferences to work with multiple frontends.

**Comment by epatpol** [comment]
@akosyakov I haven't fully considered the changes yet, but I guess this won't affect how the backend can still access the preferences right? Because PreferenceService would still be useable in the frontend/backend. It's just the injected PreferenceServer (server name is subject to change) will move to frontend to have it parsed there, wdyt?

**Comment by akosyakov** [comment]
There should not be `PreferenceService` in the backend, it should be implemented in the frontend based on the user storage service instead of the preference server.

**Comment by epatpol** [comment]
Yes that I get, my concern was more about using preferences in backend services, I guess those services would need to have a frontend proxy that would then send them the preferences right?

**Comment by akosyakov** [comment]
They should not be used, they will receive values from the frontend via a corresponding service API. Do you have a concrete case in mind? I don't think that there is a backend service using preferences at the moment.

**Comment by epatpol** [comment]
No not really I was just thinking, but it's true that right now there's no backend services using the preferences, so I'm probably just overthinking.

**Comment by epatpol** [comment]
I've started working on that [here](https://github.com/epatpol/theia-1/commit/63eda7373a62daebdfac6a42554405de711af973).

Here's what I thought of doing @akosyakov 

Have a common `PreferenceService` interface (kinda like the old `PreferenceServer` interface). Have three impl of `PreferenceService` i.e `PreferenceServiceUser` `PreferenceServiceWorkspace` and `CompoundPreferenceService`. I wanted to have to modify preference-proxy the least if possible, but when I started implementing `PreferenceServiceUser` and `CompoundPreferenceService`, I ended up thinking maybe it'd be better if the specific services just send all the preferences every time to the Compound one (all or nothing), and then the compound one could iterate over them and merge them if needed (for scoping). 

However by doing that I end up with a different interface needed for the impl and the preference-proxy whereas the proxy receives preference events one by one. Should I just extract CompoundPreferenceService to not be implementing PreferenceService? That seems to be the best but I don't know which drawbacks come from this choice. I.e we could have `PreferenceProvider` which provide preferences from either user storage/workspace/something else and `PreferenceService` which is really the class that aggregates all of this.

Also for scopes, I would really like to add them correctly in the next PR, and we would need to find a way for preference events coming from the `PreferenceProvider` to tell from which provider they came, so that the service can then calculate which one is the most important... Otherwise I'm not sure how to do it.

Thanks!

**Comment by epatpol** [comment]
@akosyakov I just finished (mostly) a prototype for frontend preferences and the issue I'm dealing with is that cpp-preferences (binded in the backend) uses PreferenceService. I thought no services used `PreferenceService` in the backend but there's at least this one...

**Comment by akosyakov** [comment]
Why is it used there? Could it be done differently, not with preferences?

**Comment by svenefftinge** [comment]
I think that could be an env.

**Comment by hexa00** [comment]
@svenefftinge I think we should avoid having env they hard to document and setup for the user.

We should rather figure out how to have a backend service use a preference, I have a use case too in the MultiRingBuffer.

Seems like we should have a `initilize` method that receives the prefs from the frontend.

**Comment by epatpol** [comment]
The problem I see with that (or at least the one I'm not sure how to resolve yet), is what happens if you have several frontends (different c++ workspaces for instance) with different preferences and that each one of them have different settings for the C++ package, which preferences are going to take precedence? I thought we didn't want a one to one relationship between the backend services and the frontend, i.e only one LS is spawned?

Is that why @svenefftinge suggested env variables? So that you configure frontend settings with preferences, and backend server with a different mechanism at startup.

**Comment by hexa00** [comment]
@epatpol the way I see it there 3 uses-cases:

 1) The backend service requires a state that depends on the frontend. Then you should have a backend-service per frontend. Let's call that: Dynamic configuration.

 2) The backend service requires state but doesn't care about the frontend (like the terminal (MultiRingBuffer perf). Let's call that: Static configuration.

 3) The backend service is stateless in which case there's no problem the frontend just sends the prefs with the method it calls. Let's call that: no configuration.

There's also how do we set these:

 1) Dynamic configurations, we need to save a configurations per workspace of the backend-services.

 2) Static configuration: we can save only 1 configuration and keep the front ends in sync.

 3) Nothing to be done.

There's also the case where you would want some default configuration based on installation specific things like how the container for that backend service is configured.

For that I think we could have a default configuration file read by the backend-service and sent to the frontend. So that the proper defaults are in place. Then the user could modify them and its preferences would take precedence.

This could be generalized such that any backend service has its default specified in a file that comes with the service.

**Comment by svenefftinge** [comment]
I proposed the `env` because it is not a user's preference where to find `clangd` (or any other installation), but a configuration matter on the backend. For local installation the line between those two are blurry, because the user is also the administrator. But for cloud workspaces, it doesn't make sense to have a user preference telling the backend where to find its executables.

**Comment by svenefftinge** [comment]
Instead of envs we could introduce some sort of backend configuration file if you prefer that.

**Comment by hexa00** [comment]
>Instead of envs we could introduce some sort of backend configuration file if you prefer that.

Yes I would prefer that as the end of my previous comment suggests it would make it:

  - visible to the user
  - easier to auto generate
  - Possibly overridable by the user 
  - It will also remove the distinction we would have to make as to what is something that the user can override or not, since we just put all the defaults in there.

**Comment by epatpol** [comment]
@svenefftinge git module also has some backend preference i.e the polling time. And filesystem also has a backend preferences for specific watch excludes (i.e /node_modules automatically excluded etc.). Should I use env for that as well? I feel like it's already going to be a big PR to have the preferences in the frontend and backend user configurable config could be another iteration? But we're going to have to find a way to configure that eventually for sure.

**Comment by svenefftinge** [comment]
Let's revise and discuss those cases 

For the watcher we should pass the options as an explicit argument rather then using some global preference. There many different usages of file watching and our preference seems to be specific for the general file watching for the workspace, only. I.e. excluding node_modules when watching the user settings directory doesn't seem useful. I think clients will have individual options.

For git it seems to not being used at all? https://github.com/theia-ide/theia/blob/master/packages/git/src/common/git-preferences.ts
So simply removing it seems to be the right thing to do.

**Comment by akosyakov** [comment]
@epatpol done?

**Comment by epatpol** [comment]
Yes, thank you for reviewing!
