### ISSUE TITLE
Keybinding Context Broken

### ISSUE THREAD

**Issue by svenefftinge** [theia-ide/theia#819]
Filtering the right keybinding for a keycode and for command, currently ignores the context, but picks the first (active). 

It should first check the context and then whether there is an enabled handler.

**Comment by hexa00** [comment]
This is not entirely true anymore, `sortKeybindingsByPriority` gives priority to a keybinding with a context and `tryKeybindingExecution` checks if that context is active.

More code could be moved however from `tryKeybindingExecution` to `getKeybindingsForKeySequence` so that it returns only the enabled keybindings...

But I'm not sure it's useful.

@svenefftinge ok to close?
