### ISSUE TITLE
Integrate onigurama-wasm to support tmTheme syntax files

### ISSUE THREAD

**Issue by colemickens** [theia-ide/theia#944]
https://github.com/rebornix/wasm-oniguruma

Not sure what the project's stance on browser compatibility is, but if we can target `wasm`, then we could great increase the number of supported languages from a syntax highlighting standpoint. (And frankly, I'd rather work on that (if I'm qualified for anything involving JS build systems...) then work on a Monarch syntax for the various languages I want to use with Theia.

Thoughts? (Note: I have no idea the status of `wasm-onigurama` other than it being somewhat active recently.)

cc: @rebornix

**Comment by colemickens** [comment]
ref: [Future Plans? (on wasm-onigurama)](https://github.com/rebornix/wasm-oniguruma/issues/1)

**Comment by svenefftinge** [comment]
@colemickens In that references ticket you state:

> I've heard that VS Code was intended to start as a fully in-browser thing, but was partially abandoned due to the need for tmTheme/onigurama.

Where have you heard that? AFAIK the monaco started as fully browser (Visual Studio Online), but vs code has been intentionally be designed to be a desktop app from the start. Before we started with Theia, we checked whether we could change vs code to run in the browser, but the architecture (lots of fine-grained communication with node processes) didn't seem appropriate. I doubt the syntax coloring was a decision maker here.

**Comment by svenefftinge** [comment]
re: wasm-onigurama

I recall seeing a comment somewhere that they tried to transpile onigurama with emscripten (or something similar) but it was much too slow. I cannot find that comment anymore, unfortunately.
Only this one: https://github.com/Microsoft/vscode/issues/174#issuecomment-158083640

**Comment by svenefftinge** [comment]
Anyways, thanks for the pointer we should watch that space, for sure :)

**Comment by colemickens** [comment]
Here's what I've seen: The monaco-editor readme implies that onigurama built with emscripten targetting asm.js was too slow. I expect wasm to be different. (Ctrl+f "onigurama" on https://github.com/Microsoft/monaco-editor)

I've not seen any perf results of the new project I linked (nor do I have any if it builds and works, but the author added at least some tests).

TBH, I don't have a source for VS Code starting as a web browser based IDE. I don't know if I'm making that up, it was based on internal info, or if I just can't find the source now. Anyway, I was under the impression it was /very/ early on, so it may have been during exploratory phases before any of the IPC type stuff was designed, as I also am familiar with the fact that the extension model wouldn't translate to the web IDE well due to the API exposed.  But really I should stop talking about it until I get a source one way or the other.

Anyway, thought it was interesting. It may not be worth keeping this open right now, which is fine with me of course.

**Comment by rebornix** [comment]
Didn't see this notification last year, hope it's not too late to respond. Disclaimer: I work on VSCode, majorly Monaco, the editor. wasm-onigurama is a hobby project I did while I was in paternal leave. I saw it as a way to get hands dirty with wasm so that's why I didn't finally integrate it with vscode or monaco.

> transpile onigurama with emscripten (or something similar) but it was much too slow

It depends on what we are comparing to. In webkit+nodejs environment, we can write heavy computation stuff in native code and hook it up through nodejs native module, that's also how we wrote [vscode-textmate](https://github.com/Microsoft/vscode-textmate). When we compared wasm with nodejs native module two years ago, wasm was too slow because browsers didn't have good support yet, wasm toolchains didn't have good enough code optimization, or maybe we wrote bad code.

Moreover, file sizes in vscode are usually way larger than standalone monaco. Few ppl open MB files in browsers but it's common in desktop editors. When the file is small, the time difference between node native module and wasm may be small, but the file size increases, wasm becomes *too slow*.

IMHO, it's possible to make wasm code as fast as (or close to) native code but the cost is complex architecture and code (Vyacheslav Egorov had a good blog post http://mrale.ph/blog/2011/11/05/the-trap-of-the-performance-sweet-spot.html). From this perspective, wasm won't give VSCode any benefit at this moment.

However for Monaco, it might be different. In browsers, usually ppl don't work on large files so performance of a wasm based tokenizer may not be the bottleneck, especially when wasm is more and more mature. The benefits are obvious, better syntax highlighting, enormous themes from TextMate/Subl/Atom/Code, etc ... AFAIK, StackBlitz used decorations to draw more colors to text instead of using Monarch. It's a workaround but it works well ;)

**Comment by simark** [comment]
Just an idea if we decide to use this.  Maybe we could use onigurama-wasm in the browser frontend but the regular onigurama in the electron frontend.  So you get the native performance if you use the electron frontend.

**Comment by svenefftinge** [comment]
Here's the comment I was referring to earlier : 
```
- all the regular expressions in TM grammars are based on oniguruma, a regular expression library written in C.
- the only way to interpret the grammars and get anywhere near original fidelity is to use the exact same regular expression library (with its custom syntax constructs) in VSCode, our runtime is node.js and we can use a node native module that exposes the library to JavaScript

- in the Monaco Editor, we are constrained to a browser environment where we cannot do anything similar

- we have experimented with Emscripten to compile the C library to asm.js, but performance was very poor even in Firefox (10x slower) and extremely poor in Chrome (100x slower).

- we can revisit this once WebAssembly gets traction in the major browsers, but we will still need to consider the browser matrix we support. i.e. if we support IE11 and only Edge will add WebAssembly support, what will the experience be in IE11, etc.
```
It is from Feb 2017.
https://news.ycombinator.com/item?id=13599908

**Comment by rebornix** [comment]
@svenefftinge thanks Sven, I talked with Alex last year about the perf results of wasm/c++ and we agreed that at some point we should revisit the benchmark (especially when we drop IE11 support). If the perf is already good, then maybe it can be an optional theme provider.

**Comment by svenefftinge** [comment]
@rebornix did you see https://github.com/NeekSandhu/onigasm?
In the readme the author claims it is only 2x slower than the node version.

**Comment by rebornix** [comment]
@svenefftinge I didn't give it a look yet. If it's just 2x slower, then the result is really good. And the benchmark for typescript languageService.js is acceptable. I'll try to do some integration with Monaco with it and see the overall performance. The only thing I worry about is the data transfer, if we don't use SAB then it can be a bottleneck when users editing content (we don't want to manage an incrementally updated buffer in wasm definitely).

**Comment by NeekSandhu** [comment]
I don't really know much about how `theia` or `monaco-editor` handles text buffers internally, but for the [IDE that I'm working on](https://goo.gl/qVnbmD), I'm using [monaco-textmate](https://github.com/NeekSandhu/monaco-textmate) with `CodeMirror` and as of current implementation no text stays inside WASM runtime.

Every keystroke, causes all the text in current line and text following the cursor to be encoded from `utf-16` to `utf-16`, `malloc`'d, then sent over to WASM runtime, processed by `oniguruma` and immediately `free`'d when results come in.

It might be better to keep a copy of text buffer in WASM runtime as long as the file/tab is open and instead of encoding almost entire file we can just send the diff/delta and apply those transformations on WASM side.

I think `theia` and IDE I'm working on share similar problems. Together we can get closer to perfection in every component. I'm gonna set up the repo very soon and hope to get more geniuses on board.

**Comment by svenefftinge** [comment]
done.
